import {serve} from 'https://deno.land/std@0.177.0/http/server.ts';
import {getSupabaseAdmin} from '../_shared/supabaseClient.ts';
import {handleOptions,jsonResponse,getOrigin} from '../_shared/cors.ts';
import {validateAdminSession,extractSessionToken} from '../_shared/adminAuth.ts';
import {centralRateLimit} from '../_shared/rateLimit.ts';
import {normalizeAssistantText} from '../_shared/assistantMatch.ts';
import {generateGroundedAssistant,relatedKnowledge,sanitizeAssistantQuestion,type AssistantSource,type ScopedKnowledge} from '../_shared/generativeAssistant.ts';

const BRAND='زینالیکید';
const ADMIN_TABS=new Set(['dashboard','data','userQuestions','assistant','reviews','consultants','courses','featured','tagged','products','services','trustbox','trust','shipping','content','images','highlights','licenses','contacts','settings','design','security','analytics','errors','trash']);
const text=(value:unknown,max:number)=>String(value||'').trim().slice(0,max);
const list=(value:unknown,maxItems=30)=>Array.isArray(value)?value.map(item=>text(item,100)).filter(Boolean).slice(0,maxItems):String(value||'').split(/[,،|\n]/).map(item=>item.trim()).filter(Boolean).slice(0,maxItems);
const safeLink=(value:unknown)=>{const link=text(value,500);return !link||(/^\/(?!admin(?:\/|$))/i.test(link))?link:''};
const safeTab=(value:unknown)=>{const tab=text(value,50);return ADMIN_TABS.has(tab)?tab:'dashboard'};
const publicItem=(source:any)=>({question:text(source?.question,500),answer:text(source?.answer,6000),aliases:list(source?.aliases),keywords:list(source?.keywords),category:text(source?.category||'عمومی',80),link_url:safeLink(source?.link_url),link_label:text(source?.link_label,100),source_url:safeLink(source?.source_url),status:source?.status==='published'?'published':'draft',is_active:source?.is_active!==false,priority:Math.max(-100,Math.min(100,Number(source?.priority)||0)),created_by:text(source?.created_by||'admin-panel',40)});
const adminItem=(source:any)=>({question:text(source?.question,500),answer:text(source?.answer,6000),aliases:list(source?.aliases),keywords:list(source?.keywords),category:text(source?.category||'مدیریت',80),status:source?.status==='published'?'published':'draft',is_active:source?.is_active!==false,priority:Math.max(-100,Math.min(100,Number(source?.priority)||0)),created_by:text(source?.created_by||'admin-panel',40),target_tab:safeTab(source?.target_tab),target_focus:text(source?.target_focus,120),action_label:text(source?.action_label||'رفتن به بخش مرتبط',100)});
const adminSources=(matches:ReturnType<typeof relatedKnowledge>):AssistantSource[]=>matches.map(({item,score})=>{const row=item as any;return {id:String(row.id||''),question:String(row.question||''),answer:String(row.answer||''),category:String(row.category||'مدیریت'),link_url:String(row.link_url||''),link_label:String(row.link_label||''),target_tab:String(row.target_tab||''),target_focus:text(row.target_focus,120),action_label:text(row.action_label||''),score:Math.round(score*1000)/1000}});
const actionsFrom=(sources:AssistantSource[])=>{const best=sources[0]?.score||0,minimum=Math.max(.45,best*.6);return sources.filter(source=>source.score>=minimum&&ADMIN_TABS.has(source.target_tab)).map(source=>({label:source.action_label||'رفتن به بخش مرتبط',tab:source.target_tab,focus:source.target_focus})).filter((item,index,array)=>array.findIndex(other=>other.tab===item.tab&&other.focus===item.focus)===index).slice(0,3)};
const suggestionsFrom=(sources:AssistantSource[],question:string)=>{const defaults=['چطور رمز پنل را تغییر بدهم؟','تنظیمات فرم‌ها را کجا تغییر بدهم؟','چطور یک دوره اضافه یا ویرایش کنم؟','یک مشتری را با بخشی از نام یا شماره پیدا کن'];const seen=new Set([normalizeAssistantText(question)]),result:string[]=[];for(const source of sources){const normalized=normalizeAssistantText(source.question);if(normalized&&!seen.has(normalized)){seen.add(normalized);result.push(source.question)}}for(const item of defaults){const normalized=normalizeAssistantText(item);if(!seen.has(normalized)){seen.add(normalized);result.push(item)}}return result.slice(0,4)};

const customerIntent=(value:string)=>{const n=normalizeAssistantText(value);return /(مشتری|کاربر|مراجع|ثبت نام|فرم|شماره|تلفن|کد پیگیری).{0,35}(پیدا|جستجو|بگرد|مشابه|لیست)|(پیدا|جستجو|بگرد|مشابه|لیست).{0,35}(مشتری|کاربر|مراجع|ثبت نام|فرم|شماره|تلفن|کد پیگیری)/.test(n)};
const searchTokens=(value:string)=>{const stop=new Set(['مشتری','کاربر','مراجع','ثبت','نام','فرم','شماره','تلفن','کد','پیگیری','پیدا','کن','کنم','جستجو','بگرد','مشابه','لیست','هرچی','هر','چه','با','که','رو','را','من','برای','اطلاعات']);return normalizeAssistantText(value).split(' ').filter(token=>token.length>1&&!stop.has(token)).slice(0,8)};
const maskPhone=(value:unknown)=>{const digits=String(value||'').replace(/\D/g,'');return digits.length<7?'':`${digits.slice(0,4)}***${digits.slice(-3)}`};
const maskName=(value:unknown)=>String(value||'').trim().split(/\s+/).filter(Boolean).map(part=>part.length<2?'*':`${part[0]}***${part.at(-1)}`).join(' ').slice(0,100);
async function searchCustomers(db:any,question:string,auth:any,origin:string){
 const tokens=searchTokens(question);if(!tokens.length)return jsonResponse({ok:true,answer:'برای جست‌وجو بخشی از نام، شماره تماس، کد پیگیری، نام دوره یا موضوع مشاوره را هم بنویسید.',model:'internal-private-search',sources:[],actions:[],suggestions:['مشتری را با بخشی از شماره تماس پیدا کن','ثبت‌های مربوط به یک نام را لیست کن'],customer_results:[],provider_called:false},200,origin);
 const {data,error}=await db.from('submissions').select('id,full_phone,payload,tracking_code,submission_type,order_status,consultation_status,course_id,created_at,deleted_at').is('deleted_at',null).order('created_at',{ascending:false}).limit(2000);if(error)throw error;
 const matches=(data||[]).filter((row:any)=>{const payload=row.payload&&typeof row.payload==='object'?row.payload:{};const hay=normalizeAssistantText([row.full_phone,row.tracking_code,row.submission_type,row.course_id,payload.pName,payload.pPhone,payload.fullPhone,payload.trackingCode,payload.type,payload.category,(payload.topics||[]).join(' '),payload.course?.title,payload.course?.titleEn,payload.childInfo?.name,payload.shipping?.city].join(' '));return tokens.every(token=>hay.includes(token))}).slice(0,20);
 const results=matches.map((row:any)=>{const p=row.payload||{};return {id:String(row.id),name:maskName(p.pName||p.childInfo?.name||'بدون نام'),phone:maskPhone(row.full_phone||p.fullPhone||p.pPhone),type:String(row.submission_type||p.type||((p.course||row.course_id)?'course':'consultation')),course:text(p.course?.title||p.course?.titleEn||row.course_id||'',120),topics:Array.isArray(p.topics)?p.topics.map((x:unknown)=>text(x,80)).slice(0,3):[],status:text(row.order_status||row.consultation_status||p.orderStatus||p.consultationStatus||'',80),date:String(row.created_at||p.date||'').slice(0,10)}});
 await db.from('admin_audit_logs').insert({actor_phone:auth.session.ownerPhone,session_id:String(auth.session.sessionId),action:'assistant_customer_search',target_type:'submissions',metadata:{result_count:results.length,token_count:tokens.length},success:true});
 return jsonResponse({ok:true,answer:results.length?`${results.length} نتیجه منطبق پیدا شد. شماره‌ها و نام‌ها در چت ماسک شده‌اند؛ برای جزئیات کامل پرونده را داخل پنل باز کنید.`:'نتیجه منطبقی پیدا نشد. بخشی دیگر از نام، شماره، کد پیگیری، دوره یا موضوع را امتحان کنید.',model:'internal-private-search',sources:[],actions:[],suggestions:['جست‌وجو با بخشی از شماره تماس','جست‌وجو با نام دوره یا موضوع مشاوره'],customer_results:results,provider_called:false},200,origin);
}

serve(async req=>{
 const options=handleOptions(req);if(options)return options;const origin=getOrigin(req);if(!origin)return jsonResponse({error:'Origin not allowed'},403,origin);if(req.method!=='POST')return jsonResponse({error:'Method not allowed'},405,origin);
 const body=await req.json().catch(()=>({})),token=extractSessionToken(req,body),auth=await validateAdminSession(token);if(!auth.ok)return jsonResponse({error:'دسترسی غیرمجاز'},401,origin);const action=String(body.action||'');
 const general=await centralRateLimit(req,`assistant-admin-${action}`,{maxRequests:90,windowMs:60_000,blockMs:60_000},auth.session.sessionId);if(!general.ok)return jsonResponse({error:'درخواست بیش از حد مجاز است'},429,origin);const db=getSupabaseAdmin();
 try{
  if(action==='list'){
   const [{data:knowledge,error},{data:adminKnowledge},{data:settings},{data:unanswered}]=await Promise.all([db.from('assistant_knowledge').select('*').order('priority',{ascending:false}).order('updated_at',{ascending:false}).limit(1000),db.from('assistant_admin_knowledge').select('*').order('priority',{ascending:false}).order('updated_at',{ascending:false}).limit(1000),db.from('assistant_settings').select('*').eq('key','default').maybeSingle(),db.from('assistant_unanswered').select('*').order('status').order('occurrences',{ascending:false}).order('last_seen_at',{ascending:false}).limit(300)]);if(error)throw error;return jsonResponse({knowledge:knowledge||[],adminKnowledge:adminKnowledge||[],settings:settings||{},unanswered:unanswered||[]},200,origin);
  }
  if(action==='generate_admin'||action==='generate_preview'){
   const question=sanitizeAssistantQuestion(body.question);if(normalizeAssistantText(question).length<3)return jsonResponse({error:'سؤال مدیریتی معتبر نیست'},400,origin);if(customerIntent(question))return await searchCustomers(db,question,auth,origin);
   const [{data:adminKnowledge,error},{data:publicKnowledge}]=await Promise.all([db.from('assistant_admin_knowledge').select('id,question,answer,aliases,keywords,category,priority,target_tab,target_focus,action_label').eq('status','published').eq('is_active',true).order('priority',{ascending:false}).limit(500),db.from('assistant_knowledge').select('id,question,answer,aliases,keywords,category,priority,link_url,link_label').eq('status','published').eq('is_active',true).order('priority',{ascending:false}).limit(500)]);if(error)throw error;
   const knowledge=[...(adminKnowledge||[]),...(publicKnowledge||[])] as ScopedKnowledge[],matches=relatedKnowledge(question,knowledge,6),fallbackSources=adminSources(matches);let result;let providerError='';
   try{result=await generateGroundedAssistant({question,knowledge,mode:'admin',brand:BRAND})}catch(error){providerError=String((error as Error)?.message||'MISTRAL_PROVIDER');if(providerError==='MISTRAL_RATE_LIMIT')return jsonResponse({ok:true,answer:'توکن امروز تموم شد.',model:'provider-limit',sources:[],actions:[],suggestions:[],customer_results:[],provider_called:false,provider_notice:'MISTRAL_RATE_LIMIT'},200,origin);result={answer:String(matches[0]?.item?.answer||''),model:'internal-fallback',sources:fallbackSources,providerCalled:false}}
   const answer=result.answer||'در دانش تأییدشده عمومی و مدیریتی، اطلاعات کافی برای این سؤال ندارم. می‌توانید درباره تنظیمات، فرم‌ها، دوره‌ها، محتوا، امنیت یا روندهای سایت سؤال کنید.';
   await db.from('admin_audit_logs').insert({actor_phone:auth.session.ownerPhone,session_id:String(auth.session.sessionId),action:'assistant_admin_generate',target_type:'assistant_knowledge',metadata:{provider:result.providerCalled?'mistral':'internal',model:result.model,source_count:result.sources.length,error_code:providerError.slice(0,80)},success:true});
   return jsonResponse({ok:true,answer,model:result.model,sources:result.sources,actions:actionsFrom(result.sources),suggestions:suggestionsFrom(result.sources,question),customer_results:[],provider_called:result.providerCalled,provider_notice:providerError?'پاسخ داخلی نمایش داده شد.':''},200,origin);
  }
  if(action==='save'){
   const scope=body.scope==='admin'?'admin':'public',item=scope==='admin'?adminItem(body.item):publicItem(body.item);if(item.question.length<2||item.answer.length<2)return jsonResponse({error:'سؤال و پاسخ الزامی است'},400,origin);const id=text(body.item?.id,50),table=scope==='admin'?'assistant_admin_knowledge':'assistant_knowledge',query=id?db.from(table).update(item).eq('id',id).select().single():db.from(table).insert(item).select().single(),{data,error}=await query;if(error)throw error;await db.from('admin_audit_logs').insert({actor_phone:auth.session.ownerPhone,session_id:String(auth.session.sessionId),action:id?'assistant_update':'assistant_create',target_type:table,target_id:String(data?.id||''),metadata:{status:item.status,scope},success:true});return jsonResponse({item:data,scope},200,origin);
  }
  if(action==='delete'){
   const scope=body.scope==='admin'?'admin':'public',id=text(body.id,50),table=scope==='admin'?'assistant_admin_knowledge':'assistant_knowledge';if(!id||body.confirm!==true)return jsonResponse({error:'تأیید حذف لازم است'},400,origin);const {error}=await db.from(table).delete().eq('id',id);if(error)throw error;await db.from('admin_audit_logs').insert({actor_phone:auth.session.ownerPhone,session_id:String(auth.session.sessionId),action:'assistant_delete',target_type:table,target_id:id,metadata:{scope},success:true});return jsonResponse({ok:true},200,origin);
  }
  if(action==='settings'){
   const settings={enabled:body.settings?.enabled!==false,welcome_message:text(body.settings?.welcome_message,1000),fallback_message:text(body.settings?.fallback_message,1500),disclaimer:text(body.settings?.disclaimer,1200),admin_block_message:text(body.settings?.admin_block_message,1500),suggested_questions:Array.isArray(body.settings?.suggested_questions)?body.settings.suggested_questions.slice(0,10):[]},{data,error}=await db.from('assistant_settings').update(settings).eq('key','default').select().single();if(error)throw error;return jsonResponse({settings:data},200,origin);
  }
  if(action==='unanswered_status'){const id=Number(body.id),status=['pending','resolved','ignored'].includes(body.status)?body.status:'pending';if(!Number.isSafeInteger(id))return jsonResponse({error:'شناسه معتبر نیست'},400,origin);const {error}=await db.from('assistant_unanswered').update({status}).eq('id',id);if(error)throw error;return jsonResponse({ok:true},200,origin)}
  if(action==='batch_import'){
   const incoming=Array.isArray(body.items)?body.items.slice(0,150):[],{data:existing}=await db.from('assistant_knowledge').select('question'),known=new Set((existing||[]).map((item:any)=>String(item.question||'').trim().toLowerCase())),rows=incoming.map(publicItem).filter(item=>item.question.length>1&&item.answer.length>1&&!known.has(item.question.toLowerCase()));if(!rows.length)return jsonResponse({ok:true,imported:0},200,origin);const {error}=await db.from('assistant_knowledge').insert(rows);if(error)throw error;await db.from('admin_audit_logs').insert({actor_phone:auth.session.ownerPhone,session_id:String(auth.session.sessionId),action:'assistant_import',target_type:'assistant_knowledge',metadata:{count:rows.length},success:true});return jsonResponse({ok:true,imported:rows.length},200,origin);
  }
  return jsonResponse({error:'Action not allowed'},400,origin);
 }catch(error){console.error('assistant-admin:',String((error as Error)?.message||error));return jsonResponse({error:'عملیات دستیار انجام نشد'},500,origin)}
});
