import {serve} from 'https://deno.land/std@0.177.0/http/server.ts';
import {getSupabaseAdmin} from '../_shared/supabaseClient.ts';
import {matchKnowledge} from '../_shared/assistantMatch.ts';
const token=()=>String(Deno.env.get('ASSISTANT_TELEGRAM_BOT_TOKEN')||'').trim();
const owner=()=>String(Deno.env.get('ASSISTANT_TELEGRAM_OWNER_CHAT_ID')||'').trim();
const webhookSecret=()=>String(Deno.env.get('ASSISTANT_TELEGRAM_WEBHOOK_SECRET')||'').trim();
const send=async(chatId:string,text:string)=>{if(!token())return;try{await fetch(`https://api.telegram.org/bot${token()}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text,disable_web_page_preview:true}),signal:AbortSignal.timeout(6000)})}catch{}};
const help=`دستورات مدیریت دانش زینالیکید:
/add — افزودن دانش عمومی یا مدیریتی
/list — ۱۰ مورد آخر هر دو بخش
/test سؤال — آزمایش دانش عمومی
/test_admin سؤال — آزمایش دانش مدیریتی
/unanswered — سؤال‌های عمومی بدون پاسخ
/publish ID — انتشار
/draft ID — بازگرداندن به پیش‌نویس
/delete ID CONFIRM — حذف قطعی
/cancel — لغو عملیات فعلی
/help — راهنما`;
const short=(id:unknown)=>String(id||'').slice(0,8);
const tables=['assistant_knowledge','assistant_admin_knowledge'] as const;
async function resolveId(db:any,prefix:string){const value=String(prefix||'').trim().toLowerCase();if(!/^[0-9a-f-]{4,36}$/.test(value))return null;const found:any[]=[];for(const table of tables){const {data}=await db.from(table).select('id').limit(1000);for(const item of data||[])if(String(item.id).toLowerCase().startsWith(value))found.push({id:item.id,table,scope:table==='assistant_knowledge'?'عمومی':'مدیریتی'})}return found.length===1?found[0]:null}
serve(async req=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});if(!webhookSecret()||req.headers.get('X-Telegram-Bot-Api-Secret-Token')!==webhookSecret())return new Response('Forbidden',{status:403});
 const update=await req.json().catch(()=>({})),message=update?.message;if(!message)return Response.json({ok:true});const chatId=String(message?.chat?.id||''),incoming=String(message?.text||'').trim();if(!chatId||chatId!==owner()||message?.chat?.type!=='private')return Response.json({ok:true});const db=getSupabaseAdmin();
 try{
  if(incoming==='/start'||incoming==='/help'){await send(chatId,`مالک تأیید شد.\n\n${help}`);return Response.json({ok:true})}
  if(incoming==='/cancel'){await db.from('assistant_bot_states').delete().eq('chat_id',chatId);await send(chatId,'عملیات فعلی لغو شد.');return Response.json({ok:true})}
  if(incoming==='/add'){await db.from('assistant_bot_states').upsert({chat_id:chatId,step:'scope',draft:{},updated_at:new Date().toISOString()});await send(chatId,'نوع دانش را بنویسید:\nعمومی — قابل استفاده برای کاربران سایت\nمدیریتی — فقط برای مدیر داخل پنل');return Response.json({ok:true})}
  if(incoming==='/list'){const rows:any[]=[];for(const table of tables){const {data}=await db.from(table).select('id,question,status').order('updated_at',{ascending:false}).limit(10);for(const item of data||[])rows.push({...item,scope:table==='assistant_knowledge'?'عمومی':'مدیریتی'})}rows.splice(10);await send(chatId,rows.length?rows.map((item:any,index:number)=>`${index+1}. [${item.scope} · ${item.status==='published'?'منتشر':'پیش‌نویس'}] ${short(item.id)} — ${item.question}`).join('\n'):'هنوز دانشی ثبت نشده است.');return Response.json({ok:true})}
  if(incoming==='/unanswered'){const {data}=await db.from('assistant_unanswered').select('id,question,occurrences').eq('status','pending').order('occurrences',{ascending:false}).limit(10);await send(chatId,(data||[]).length?(data||[]).map((item:any)=>`#${item.id} (${item.occurrences} بار) ${item.question}`).join('\n'):'سؤال بدون پاسخ وجود ندارد.');return Response.json({ok:true})}
  for(const config of [{prefix:'/test_admin ',table:'assistant_admin_knowledge',label:'مدیریتی'},{prefix:'/test ',table:'assistant_knowledge',label:'عمومی'}])if(incoming.startsWith(config.prefix)){const query=incoming.slice(config.prefix.length).trim(),fields=config.table==='assistant_knowledge'?'id,question,answer,aliases,keywords,category,link_url,link_label,priority':'id,question,answer,aliases,keywords,category,target_tab,target_focus,action_label,priority',{data}=await db.from(config.table).select(fields).eq('status','published').eq('is_active',true).limit(500),result=matchKnowledge(query,data||[],3);await send(chatId,result.length?`بهترین پاسخ ${config.label} (${Math.round(result[0].score*100)}٪):\n${result[0].item.answer}\n\nموارد مرتبط:\n${result.map(row=>`• ${row.item.question}`).join('\n')}`:`پاسخ منتشرشده ${config.label} پیدا نشد.`);return Response.json({ok:true})}
  for(const [command,status] of [['/publish ','published'],['/draft ','draft']] as const)if(incoming.startsWith(command)){const found=await resolveId(db,incoming.slice(command.length));if(!found){await send(chatId,'شناسه یکتا پیدا نشد.');return Response.json({ok:true})}await db.from(found.table).update({status}).eq('id',found.id);await send(chatId,status==='published'?`${found.scope} منتشر شد: ${short(found.id)}`:`${found.scope} به پیش‌نویس برگشت: ${short(found.id)}`);return Response.json({ok:true})}
  if(incoming.startsWith('/delete ')){const parts=incoming.split(/\s+/);if(parts[2]!=='CONFIRM'){await send(chatId,'برای حذف قطعی بنویسید: /delete ID CONFIRM');return Response.json({ok:true})}const found=await resolveId(db,parts[1]);if(!found){await send(chatId,'شناسه یکتا پیدا نشد.');return Response.json({ok:true})}await db.from(found.table).delete().eq('id',found.id);await send(chatId,`${found.scope} حذف شد: ${short(found.id)}`);return Response.json({ok:true})}
  if(incoming.startsWith('/')){await send(chatId,help);return Response.json({ok:true})}
  const {data:state}=await db.from('assistant_bot_states').select('step,draft').eq('chat_id',chatId).maybeSingle();if(!state)return Response.json({ok:true});const draft=state.draft||{};
  if(state.step==='scope'){const normalized=incoming.replace(/\s/g,'');const scope=/^(عمومی|public)$/i.test(normalized)?'public':/^(مدیریتی|مدیریت|admin)$/i.test(normalized)?'admin':'';if(!scope){await send(chatId,'فقط «عمومی» یا «مدیریتی» بنویسید:');return Response.json({ok:true})}await db.from('assistant_bot_states').update({step:'question',draft:{scope},updated_at:new Date().toISOString()}).eq('chat_id',chatId);await send(chatId,`سؤال اصلی دانش ${scope==='public'?'عمومی':'مدیریتی'} را بنویسید:`);return Response.json({ok:true})}
  if(state.step==='question'){if(incoming.length<2){await send(chatId,'سؤال خیلی کوتاه است.');return Response.json({ok:true})}await db.from('assistant_bot_states').update({step:'answer',draft:{...draft,question:incoming},updated_at:new Date().toISOString()}).eq('chat_id',chatId);await send(chatId,'پاسخ تأییدشده را بنویسید:');return Response.json({ok:true})}
  if(state.step==='answer'){if(incoming.length<2){await send(chatId,'پاسخ خیلی کوتاه است.');return Response.json({ok:true})}await db.from('assistant_bot_states').update({step:'keywords',draft:{...draft,answer:incoming},updated_at:new Date().toISOString()}).eq('chat_id',chatId);await send(chatId,'کلمات کلیدی را با ویرگول جدا کنید؛ اگر ندارید - بفرستید:');return Response.json({ok:true})}
  if(state.step==='keywords'){const keywords=incoming==='-'?[]:incoming.split(/[,،]/).map((value:string)=>value.trim()).filter(Boolean).slice(0,30);await db.from('assistant_bot_states').update({step:'category',draft:{...draft,keywords},updated_at:new Date().toISOString()}).eq('chat_id',chatId);await send(chatId,'دسته‌بندی را بنویسید؛ اگر ندارید - بفرستید:');return Response.json({ok:true})}
  if(state.step==='category'){await db.from('assistant_bot_states').update({step:'target',draft:{...draft,category:incoming==='-'?(draft.scope==='admin'?'مدیریت':'عمومی'):incoming.slice(0,80)},updated_at:new Date().toISOString()}).eq('chat_id',chatId);await send(chatId,draft.scope==='admin'?'مقصد پنل را با این قالب بفرستید:\nsecurity | تغییر اطلاعات ورود | رفتن به امنیت\nاگر مقصد ندارید - بفرستید.':'لینک و عنوان دکمه را با این قالب بفرستید:\n/courses | مشاهده دوره‌ها\nاگر ندارید - بفرستید.');return Response.json({ok:true})}
  if(state.step==='target'){
   const parts=incoming==='-'?[]:incoming.split('|').map((value:string)=>value.trim()),table=draft.scope==='admin'?'assistant_admin_knowledge':'assistant_knowledge';
   const row=draft.scope==='admin'?{question:draft.question,answer:draft.answer,keywords:draft.keywords||[],category:draft.category||'مدیریت',target_tab:String(parts[0]||'dashboard').slice(0,50),target_focus:String(parts[1]||'').slice(0,120),action_label:String(parts[2]||'رفتن به بخش مرتبط').slice(0,100),status:'draft',created_by:'telegram'}:{question:draft.question,answer:draft.answer,keywords:draft.keywords||[],category:draft.category||'عمومی',link_url:String(parts[0]||'').startsWith('/')?String(parts[0]).slice(0,500):'',link_label:String(parts[1]||'مشاهده بخش مرتبط').slice(0,100),status:'draft',created_by:'telegram'};
   const {data,error}=await db.from(table).insert(row).select('id').single();await db.from('assistant_bot_states').delete().eq('chat_id',chatId);await send(chatId,error?'ثبت انجام نشد. دوباره /add را شروع کنید.':`پیش‌نویس ${draft.scope==='admin'?'مدیریتی':'عمومی'} ذخیره شد: ${short(data.id)}\nبرای انتشار: /publish ${short(data.id)}`);return Response.json({ok:true})
  }
  return Response.json({ok:true});
 }catch(error){console.error('assistant-telegram',String((error as Error)?.message||error));await send(chatId,'خطای موقت رخ داد. دوباره تلاش کنید.');return Response.json({ok:true})}
});
