import {useEffect,useMemo,useRef,useState} from 'react';
import type {DynamicRecord} from '../app/AppContext';
import {fetchAssistantData,generateAssistantAnswer,type AssistantAction,type AssistantPublicData,type AssistantSuggestion} from '../lib/assistantApi';
import GuideHeadsetIcon from './GuideHeadsetIcon';
import './assistant-widget.css';

type Message={role:'assistant'|'user';text:string;actions?:AssistantAction[];suggestions?:AssistantSuggestion[]};
type Guidance={stage:'goal'|'age'|'metrics';original:string;goal?:string;age?:string};
const normalizeDigits=(value:string)=>value.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));
const guidedIntent=(value:string)=>/(مکمل|رشد قد|افزایش قد|کوتاه قد|وزن.?گیری|بی.?اشتهایی|بدغذایی|تمرکز|هوش|تقویت ایمنی|دوره.*فرزند|دوره.*بچه)/i.test(value);
const hasAge=(value:string)=>/\b(?:[2-9]|1[0-8])\s*(?:سال|ساله)?\b/.test(normalizeDigits(value));
const suggestion=(question:string,label=question):AssistantSuggestion=>({question,label,path:''});

export default function AssistantWidget({T,lang}:{T:DynamicRecord;lang:'fa'|'en'}){
 const [data,setData]=useState<AssistantPublicData|null>(null),[open,setOpen]=useState(false),[input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[guidance,setGuidance]=useState<Guidance|null>(null);const endRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLInputElement|null>(null),en=lang==='en';
 useEffect(()=>{let alive=true;fetchAssistantData().then(value=>{if(alive){setData(value);setMessages([{role:'assistant',text:value.settings.welcome_message,suggestions:value.settings.suggested_questions}])}}).catch(()=>{});return()=>{alive=false}},[]);
 useEffect(()=>{if(open){setTimeout(()=>inputRef.current?.focus(),100);setTimeout(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),80)}},[open,messages.length,busy]);
 const initialSuggestions=useMemo(()=>data?.settings.suggested_questions?.length?data.settings.suggested_questions:(data?.knowledge||[]).slice(0,4).map(item=>({question:item.question,label:item.question,path:item.link_url||''})),[data]);if(!data?.settings.enabled)return null;
 const requestAnswer=async(question:string,displayText=question,healthFlow=false)=>{setMessages(current=>[...current,{role:'user',text:displayText}]);setBusy(true);try{const result=await generateAssistantAnswer(question),healthActions:AssistantAction[]=healthFlow?[{label:'مشاهده دوره‌ها',path:'/courses'},{label:'ثبت درخواست مشاوره',path:'/consultation'}]:[],actions=[...(result.actions||[]),...healthActions].filter((item,index,array)=>array.findIndex(other=>other.path===item.path)===index).slice(0,3);setMessages(current=>[...current,{role:'assistant',text:result.answer,actions,suggestions:result.suggestions?.length?result.suggestions:initialSuggestions}])}catch(reason){setMessages(current=>[...current,{role:'assistant',text:String((reason as Error)?.message||'دستیار موقتاً در دسترس نیست.'),suggestions:initialSuggestions}])}finally{setBusy(false)}};
 const ask=async(value=input)=>{const question=value.trim();if(question.length<2||busy)return;setInput('');
  if(guidance){
   if(question==='لغو'){setGuidance(null);setMessages(current=>[...current,{role:'user',text:question},{role:'assistant',text:'راهنمای مرحله‌ای لغو شد.',suggestions:initialSuggestions}]);return}
   if(guidance.stage==='goal'){setGuidance({...guidance,stage:'age',goal:question});setMessages(current=>[...current,{role:'user',text:question},{role:'assistant',text:'سن فرزندتان چند سال است؟',suggestions:[suggestion('۵ سال'),suggestion('۱۰ سال'),suggestion('۱۵ سال'),suggestion('لغو')]}]);return}
   if(guidance.stage==='age'){if(!hasAge(question)){setMessages(current=>[...current,{role:'user',text:question},{role:'assistant',text:'لطفاً سن را به سال بنویسید؛ مثلاً «۱۵ سال».',suggestions:[suggestion('۵ سال'),suggestion('۱۰ سال'),suggestion('۱۵ سال'),suggestion('لغو')]}]);return}setGuidance({...guidance,stage:'metrics',age:question});setMessages(current=>[...current,{role:'user',text:question},{role:'assistant',text:'قد و وزن تقریبی فرزندتان را بنویسید؛ مثلاً «قد ۱۵۵ سانتی‌متر و وزن ۴۸ کیلوگرم». این اطلاعات فقط برای انتخاب راهنمای عمومی دوره استفاده می‌شود.',suggestions:[suggestion('اطلاعات قد و وزن را ندارم'),suggestion('لغو')]}]);return}
   const goal=guidance.goal||'راهنمایی عمومی',retrieval=/رشد|قد/.test(goal)?'چه سنینی برای افزایش رشد قد مناسب است؟':/اشتها|وزن|بدغذا/.test(goal)?'چرا فرزندم بدغذا شده است؟':/تمرکز|هوش|یادگیری/.test(goal)?'چه مواد مغذی برای تمرکز کودک مهم است؟':`کدام دوره برای ${goal} مناسب است؟`,composed=`${retrieval}\nهدف یا مشکل: ${goal}\nسن فرزند: ${guidance.age||''}\nقد و وزن تقریبی: ${question}\nفقط از دوره‌های منتشرشده سایت پیشنهاد بده؛ مکمل مشخص یا نتیجه قطعی پیشنهاد نده.`;setGuidance(null);await requestAnswer(composed,question,true);return;
  }
  if(guidedIntent(question)&&!hasAge(question)){setGuidance({stage:'goal',original:question});setMessages(current=>[...current,{role:'user',text:question},{role:'assistant',text:'برای چه هدف یا مشکلی راهنمایی می‌خواهید؟ برای نمونه رشد قد، وزن‌گیری، بی‌اشتهایی، تمرکز یا موضوع دیگری.',suggestions:[suggestion('رشد قد'),suggestion('وزن‌گیری و اشتها'),suggestion('تمرکز و یادگیری'),suggestion('لغو')]}]);return}
  await requestAnswer(question,question,guidedIntent(question));
 };
 return <><button type="button" className="zka-launch" aria-label={en?'Open site guide':'بازکردن راهنمای سایت'} aria-expanded={open} onClick={()=>setOpen(value=>!value)} style={{background:T.card||T.pop,color:T.acc,borderColor:T.brd,boxShadow:T.shadowLight||T.neuOut}}><GuideHeadsetIcon size={29}/></button>{open&&<section className="zka-panel" role="dialog" aria-modal="false" aria-label={en?'Site guide':'راهنمای سایت'} style={{background:T.pop||T.card,borderColor:T.brd,boxShadow:T.shadowStrong||'0 24px 70px rgba(0,0,0,.25)'}}><header className="zka-head" style={{background:T.grad||T.acc}}><GuideHeadsetIcon size={31}/><button type="button" aria-label={en?'Close':'بستن'} onClick={()=>setOpen(false)}>×</button></header><div className="zka-messages" role="log" aria-live="polite">{messages.map((message,index)=><div key={index} className={`zka-turn ${message.role}`}><div className={`zka-message ${message.role}`} style={message.role==='assistant'?{background:T.soft,color:T.txt}:{background:T.acc,color:'#fff'}}>{message.text}</div>{message.actions?.length?<div className="zka-actions">{message.actions.map(action=><a key={`${action.path}-${action.label}`} href={action.path} style={{borderColor:T.acc,color:T.acc}}>{action.label}</a>)}</div>:null}{message.role==='assistant'&&message.suggestions?.length?<div className="zka-next" aria-label="پرسش‌های پیشنهادی">{message.suggestions.map(item=><button type="button" key={`${index}-${item.question}`} onClick={()=>ask(item.question)} style={{borderColor:T.brd,color:T.txt}}>{item.label||item.question}</button>)}</div>:null}</div>)}{busy&&<div className="zka-turn assistant"><div className="zka-message assistant zka-typing" style={{background:T.soft,color:T.txt}}><i/><i/><i/></div></div>}<div ref={endRef}/></div><form className="zka-form" onSubmit={event=>{event.preventDefault();ask()}}><input ref={inputRef} value={input} maxLength={500} onChange={event=>setInput(event.target.value)} placeholder={en?'Type your question…':'سؤال خود را بنویسید…'} style={{borderColor:T.brd,background:T.inp,color:T.txt}}/><button type="submit" aria-label="ارسال سؤال" disabled={input.trim().length<2||busy} style={{background:T.grad||T.acc}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg></button></form><footer style={{color:T.mut}}>{data.settings.disclaimer}<br/><span>{en?'Do not enter phone numbers or private medical details.':'شماره تماس یا اطلاعات پزشکی خصوصی وارد نکنید.'}</span></footer></section>}</>;
}
