import {useEffect,useLayoutEffect,useRef,useState,type RefObject} from 'react';
import {PROJECT_CODE} from '../config/project';

type HintKind='initial'|'five'|'nine';
type Position={left:number;top:number;width:number;connector:number;placement:'above'|'below'};
const textFor=(kind:HintKind,en:boolean)=>{
 if(en){if(kind==='initial')return {title:'We are here to guide you',text:'Have a question? Open the site guide for a quicker path.'};if(kind==='five')return {title:'Need a little guidance?',text:'The site guide can help you find the right section.'};return {title:'Looking for something specific?',text:'Ask the guide and reach the relevant section faster.'}}
 if(kind==='initial')return {title:'همراه شما هستیم',text:'اگر سوالی دارین، راهنمای سایت در دسترس شماست.'};if(kind==='five')return {title:'راهنمایی لازم دارین؟',text:'برای پیدا کردن مسیر درست، از راهنمای سایت کمک بگیرین.'};return {title:'دنبال بخش خاصی هستین؟',text:'سوالتون رو بپرسین تا سریع تر به بخش مرتبط برسین.'};
};
export default function AssistantDiscoveryHint({lang,anchorRef,onOpen,onVisibilityChange}:{lang:'fa'|'en';anchorRef:RefObject<HTMLElement|null>;onOpen:()=>void;onVisibilityChange:(visible:boolean)=>void}){
 const [kind,setKind]=useState<HintKind|null>(null),[leaving,setLeaving]=useState(false),[position,setPosition]=useState<Position|null>(null);const elapsed=useRef(0),last=useRef(Date.now()),cardRef=useRef<HTMLButtonElement|null>(null);const prefix=`${PROJECT_CODE}_assistant_discovery_`;
 const dismiss=()=>{if(!kind||leaving)return;setLeaving(true);setTimeout(()=>{setKind(null);setLeaving(false);setPosition(null)},320)};
 useEffect(()=>{onVisibilityChange(Boolean(kind));return()=>onVisibilityChange(false)},[kind,onVisibilityChange]);
 useEffect(()=>{try{elapsed.current=Number(sessionStorage.getItem(prefix+'elapsed')||0)}catch{}last.current=Date.now();setKind('initial');const tick=window.setInterval(()=>{const now=Date.now();if(document.visibilityState==='visible')elapsed.current+=Math.max(0,now-last.current);last.current=now;try{sessionStorage.setItem(prefix+'elapsed',String(elapsed.current));const five=sessionStorage.getItem(prefix+'five')==='1',nine=sessionStorage.getItem(prefix+'nine')==='1';if(elapsed.current>=540000&&!nine){sessionStorage.setItem(prefix+'nine','1');setKind('nine')}else if(elapsed.current>=300000&&!five){sessionStorage.setItem(prefix+'five','1');setKind('five')}}catch{}},1000);const visibility=()=>{last.current=Date.now()};document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(tick);document.removeEventListener('visibilitychange',visibility);try{sessionStorage.setItem(prefix+'elapsed',String(elapsed.current))}catch{}}},[prefix]);
 useLayoutEffect(()=>{if(!kind)return;let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const anchor=anchorRef.current,card=cardRef.current;if(!anchor||!card)return;const a=anchor.getBoundingClientRect(),c=card.getBoundingClientRect(),safe=10,connectorGap=30,center=a.left+a.width/2,availableWidth=Math.max(0,window.innerWidth-safe*2),naturalWidth=Math.min(300,Math.max(c.width,card.scrollWidth)),width=Math.min(naturalWidth,availableWidth),preferredLeft=center-width/2,left=Math.max(safe,Math.min(preferredLeft,window.innerWidth-width-safe)),top=Math.max(a.bottom+connectorGap,safe),connector=center-left;setPosition({left,top:Math.min(top,window.innerHeight-c.height-safe),width,connector,placement:'below'})})};update();window.addEventListener('resize',update);window.addEventListener('orientationchange',update);window.addEventListener('scroll',update,{passive:true});const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(update):null;if(anchorRef.current)observer?.observe(anchorRef.current);if(cardRef.current)observer?.observe(cardRef.current);return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',update);window.removeEventListener('orientationchange',update);window.removeEventListener('scroll',update);observer?.disconnect()}},[kind,anchorRef]);
 useEffect(()=>{if(!kind)return;const hide=()=>dismiss(),autoHide=window.setTimeout(hide,5000);window.addEventListener('scroll',hide,{passive:true,once:true});document.addEventListener('pointerdown',hide,{passive:true,once:true,capture:true});return()=>{clearTimeout(autoHide);window.removeEventListener('scroll',hide);document.removeEventListener('pointerdown',hide,true)}},[kind]);
 if(!kind)return null;const copy=textFor(kind,lang==='en');
 return <button ref={cardRef} type="button" className={`zka-discovery ${leaving?'is-leaving':''} ${position?'is-positioned':''}`} style={position?{left:position.left,top:position.top,width:position.width}:undefined} onClick={onOpen} aria-label={`${copy.title}. ${copy.text}`}>
  <span className={`zka-discovery-connector is-${position?.placement||'below'}`} style={position?{left:position.connector}:undefined} aria-hidden="true"/>
  <span className="zka-discovery-copy" dir={lang==='en'?'ltr':'rtl'}><b>{copy.title}</b><small>{copy.text}</small></span>
 </button>;
}
