import {useEffect,useRef,useState} from 'react';
import type {DynamicRecord} from '../app/AppContext';
import {assistantAdminGenerate,type AssistantAdminAction,type AssistantCustomerResult} from '../lib/assistantAdminApi';
import GuideHeadsetIcon from '../components/GuideHeadsetIcon';
import './admin-assistant-widget.css';

type AdminMessage={role:'assistant'|'user';text:string;actions?:AssistantAdminAction[];suggestions?:string[];customerResults?:AssistantCustomerResult[]};
const defaults=['چطور رمز پنل را تغییر بدهم؟','تنظیمات فرم‌ها را کجا تغییر بدهم؟','چطور یک دوره اضافه یا ویرایش کنم؟','یک مشتری را با بخشی از نام یا شماره پیدا کن'];
export default function AdminAssistantWidget({T,onNavigate}:{T:DynamicRecord;onNavigate:(tab:string,focus:string,recordId?:string)=>void}){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[messages,setMessages]=useState<AdminMessage[]>([{role:'assistant',text:'درباره تنظیمات، روندهای سایت یا جست‌وجوی مشتریان از من بپرسید.',suggestions:defaults}]);
 const inputRef=useRef<HTMLInputElement|null>(null),endRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(open){setTimeout(()=>inputRef.current?.focus(),100);setTimeout(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),80)}},[open,messages.length,busy]);
 const ask=async(value=input)=>{const question=value.trim();if(question.length<3||busy)return;setInput('');setMessages(current=>[...current,{role:'user',text:question}]);setBusy(true);try{const result=await assistantAdminGenerate(question);setMessages(current=>[...current,{role:'assistant',text:result.answer,actions:result.actions,suggestions:result.suggestions?.length?result.suggestions:defaults,customerResults:result.customer_results||[]}])}catch(error){setMessages(current=>[...current,{role:'assistant',text:String((error as Error)?.message||'دستیار مدیریتی موقتاً در دسترس نیست.'),suggestions:defaults}])}finally{setBusy(false)}};
 return <>
  <button data-testid="admin-assistant-launch" type="button" className="zkaa-launch" aria-label="بازکردن راهنمای پنل مدیریت" aria-expanded={open} onClick={()=>setOpen(value=>!value)} style={{background:T.grad||T.acc}}><GuideHeadsetIcon size={29}/></button>
  {open&&<section data-testid="admin-assistant-panel" className="zkaa-panel" role="dialog" aria-label="راهنمای پنل مدیریت" style={{background:T.pop||T.card,borderColor:T.brd}}>
   <header className="zkaa-head" style={{background:T.grad||T.acc}}><GuideHeadsetIcon size={31}/><button type="button" aria-label="بستن" onClick={()=>setOpen(false)}>×</button></header>
   <div className="zkaa-messages" role="log" aria-live="polite">{messages.map((message,index)=><div key={index} className={`zkaa-turn ${message.role}`}><div className={`zkaa-message ${message.role}`} style={message.role==='assistant'?{background:T.soft,color:T.txt}:{background:T.acc,color:'var(--zkad-acc-contrast, #fff)'}}>{message.text}</div>{message.customerResults?.length?<div className="zkaa-customers">{message.customerResults.map(record=><article key={record.id} style={{borderColor:T.brd,background:T.card,color:T.txt}}><b>{record.name||'نام ثبت نشده'}</b><span>{record.phone||'شماره نامشخص'} · {record.type==='course'?'ثبت دوره':'مشاوره'} · {record.date||'بدون تاریخ'}</span>{record.course&&<span>دوره: {record.course}</span>}{record.topics?.length>0&&<span>موضوع: {record.topics.join('، ')}</span>}<button type="button" onClick={()=>{onNavigate('data','',record.id);setOpen(false)}} style={{borderColor:T.acc,color:T.acc}}>بازکردن پرونده در پنل</button></article>)}</div>:null}{message.actions?.length?<div className="zkaa-actions">{message.actions.map(action=><button type="button" key={`${action.tab}-${action.focus}-${action.record_id||''}`} onClick={()=>{onNavigate(action.tab,action.focus,action.record_id);setOpen(false)}} style={{borderColor:T.acc,color:T.acc}}>{action.label}</button>)}</div>:null}{message.role==='assistant'&&message.suggestions?.length?<div className="zkaa-next">{message.suggestions.map(question=><button type="button" key={`${index}-${question}`} onClick={()=>ask(question)} style={{borderColor:T.brd,color:T.txt}}>{question}</button>)}</div>:null}</div>)}{busy&&<div className="zkaa-turn assistant"><div className="zkaa-message assistant" style={{background:T.soft,color:T.txt}}>در حال آماده‌سازی پاسخ…</div></div>}<div ref={endRef}/></div>
   <form className="zkaa-form" onSubmit={event=>{event.preventDefault();ask()}}><input ref={inputRef} value={input} maxLength={500} onChange={event=>setInput(event.target.value)} placeholder="سؤال یا بخشی از مشخصات مشتری…" style={{background:T.inp,color:T.txt,borderColor:T.brd}}/><button type="submit" aria-label="ارسال سؤال" disabled={busy||input.trim().length<3} style={{background:T.grad||T.acc}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg></button></form>
   <footer style={{color:T.mut}}>جست‌وجوی مشتری داخل Supabase انجام می‌شود و اطلاعات آن به مدل خارجی ارسال نمی‌شود. رمز و کلید وارد نکنید.</footer>
  </section>}
 </>;
}
