import {useEffect,useMemo,useState,type CSSProperties} from 'react';
import type {DynamicRecord} from '../app/AppContext';
import {announceAssistantSettings} from '../lib/assistantApi';
import {assistantAdminClearUnanswered,assistantAdminDelete,assistantAdminExportKnowledge,assistantAdminImport,assistantAdminList,assistantAdminParseInstruction,assistantAdminResolveUnanswered,assistantAdminSave,assistantAdminSettings,assistantAdminTelegramRepair,assistantAdminTelegramStatus,assistantAdminTestKnowledge,assistantAdminUnansweredDraft,assistantAdminUnansweredStatus,type AssistantAdminData,type AssistantAdminItem,type AssistantKnowledgeSelection,type AssistantKnowledgeTestResult,type AssistantKnowledgeTestSingle,type AssistantTelegramStatus} from '../lib/assistantAdminApi';
import type {AssistantKnowledgeAction,AssistantMatchMode,AssistantResponseMode} from '../utils/assistantMatch';
import './assistant-manager.css';

const tabs=[['dashboard','داشبورد'],['data','فرم‌ها و سفارشات'],['userQuestions','سؤالات مخاطبین'],['assistant','دستیار'],['reviews','نظرات'],['consultants','مشاوران'],['courses','دوره‌ها'],['featured','دوره‌های ویژه'],['tagged','دوره‌های تگ‌دار'],['products','محصولات'],['services','خدمات'],['trustbox','اعتمادساز'],['trust','جملات موفقیت'],['shipping','ارسال و پرداخت'],['content','محتوا'],['images','تصاویر'],['highlights','هایلایت'],['licenses','مجوزها'],['contacts','ارتباط'],['settings','تنظیمات'],['design','دیزاین'],['security','امنیت'],['analytics','آمار'],['entry','صفحه ورودی'],['errors','خطاها'],['trash','سطل بازیافت']];
const paths=[['/consultation','فرم مشاوره'],['/courses','دوره‌ها'],['/track','پیگیری درخواست'],['/products','محصولات'],['/education','آموزش‌ها'],['/faq','سؤالات متداول'],['/contact','ارتباط با ما'],['/about','درباره ما'],['/experience','تجربه والدین'],['/licenses','مجوزها'],['/growth','رشد'],['/privacy','حریم خصوصی'],['/','صفحه اصلی']];
const normalizeQuestion=(value:string)=>value.trim().toLocaleLowerCase('fa').replace(/[\u200c\u200f]/g,' ').replace(/\s+/g,' ');
const empty=(scope:AssistantKnowledgeSelection):Partial<AssistantAdminItem>=>({question:'',answer:'',aliases:[],keywords:[],category:scope==='admin'?'مدیریت':scope==='public'?'عمومی':'',actions:[],link_url:'',link_label:'',source_url:'',target_tab:'dashboard',target_focus:'',action_label:'رفتن به بخش مرتبط',response_mode:'grounded',match_mode:'smart',status:'published',is_active:true,priority:0,created_by:'admin-panel',scope_presence:scope==='both'?['public','admin']:[scope]});
const splitLines=(value:string)=>value.split(/\n+/).map(item=>item.trim()).filter(Boolean).slice(0,30);
const splitList=(value:string)=>value.split(/[,،|\n]/).map(item=>item.trim()).filter(Boolean).slice(0,30);
const triggersOf=(item:Partial<AssistantAdminItem>)=>[item.question,...(item.aliases||[])].filter(Boolean).join('\n');
const modeCopy:Record<AssistantResponseMode,{title:string;desc:string}>={grounded:{title:'پاسخ طبیعی هوشمند',desc:'هوش مصنوعی فقط با همین دانش، پاسخ را طبیعی بازگو می‌کند.'},exact:{title:'پاسخ ثابت',desc:'متن پاسخ دقیقاً بدون بازنویسی نمایش داده می‌شود.'},refusal:{title:'اعلام عدم اطلاع',desc:'برای این جمله‌ها، ربات پیام «اطلاعی ندارم» دلخواه شما را می‌گوید.'}};
type PendingEditor={answer:string;aliases:string;keywords:string;notice:string;suggestedAnswer:string;suggestedNotice:string;grouped:number;preparing?:boolean;saving?:boolean};
const unansweredReason:Record<string,string>={no_match:'دانش مستقیم پیدا نشد',low_confidence:'پاسخ با اطمینان کافی نبود',generic_answer:'پاسخ کلی دریافت شد'};

export default function AssistantManager({T,cfg}:{T:DynamicRecord;S:DynamicRecord;cfg:DynamicRecord}){
  const [data,setData]=useState<AssistantAdminData|null>(null),scope='public' as AssistantKnowledgeSelection,[draft,setDraft]=useState<Partial<AssistantAdminItem>>(empty('public')),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[quick,setQuick]=useState(''),[parsing,setParsing]=useState(false),[testQuestion,setTestQuestion]=useState(''),[testing,setTesting]=useState(false),[testResult,setTestResult]=useState<AssistantKnowledgeTestResult|null>(null),[telegram,setTelegram]=useState<AssistantTelegramStatus|null>(null),[telegramBusy,setTelegramBusy]=useState(false),[exportBusy,setExportBusy]=useState(false),[deleteId,setDeleteId]=useState(''),[openUnansweredId,setOpenUnansweredId]=useState<number|null>(null),[unansweredEditors,setUnansweredEditors]=useState<Record<number,PendingEditor>>({}),[clearUnanswered,setClearUnanswered]=useState(false);
  const vars={'--zkam-acc':T.acc,'--zkam-card':T.card,'--zkam-soft':T.soft,'--zkam-text':T.txt,'--zkam-muted':T.mut,'--zkam-border':T.brd,'--zkam-ok':T.ok,'--zkam-warn':T.warn,'--zkam-error':T.err} as CSSProperties;
  const load=async()=>{setLoading(true);try{setData(await assistantAdminList())}catch(error){setMessage(String((error as Error)?.message||error))}finally{setLoading(false)}};
  const loadTelegram=async()=>{try{setTelegram((await assistantAdminTelegramStatus()).status)}catch(error){setMessage(String((error as Error)?.message||error))}};
  useEffect(()=>{load();loadTelegram()},[]);
  const items=useMemo(()=>{
    const publicItems=(data?.knowledge||[]).map(item=>({...item,public_id:item.id,source_scope:'public' as const,original_question:item.question,scope_presence:['public' as const]}));
    const adminItems=(data?.adminKnowledge||[]).map(item=>({...item,admin_id:item.id,source_scope:'admin' as const,original_question:item.question,scope_presence:['admin' as const]}));
    if(scope==='public')return publicItems;if(scope==='admin')return adminItems;
    const combined=new Map<string,AssistantAdminItem>();
    for(const item of publicItems)combined.set(normalizeQuestion(item.question),item);
    for(const adminItem of adminItems){const key=normalizeQuestion(adminItem.question),publicItem=combined.get(key);if(publicItem)combined.set(key,{...publicItem,admin_id:adminItem.id,target_tab:adminItem.target_tab,target_focus:adminItem.target_focus,action_label:adminItem.action_label,scope_presence:['public','admin']});else combined.set(key,adminItem)}
    return [...combined.values()];
  },[data,scope]);
  const visible=useMemo(()=>items.filter(item=>!search||`${item.question} ${item.answer} ${(item.aliases||[]).join(' ')} ${item.category}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const publicPublished=data?.knowledge.filter(item=>item.status==='published'&&item.is_active).length||0;
  const pendingUnanswered=data?.unanswered.filter(item=>item.status==='pending')||[];
  const set=(key:keyof AssistantAdminItem,value:unknown)=>setDraft(current=>({...current,[key]:value}));
  const changeMode=(mode:AssistantResponseMode)=>setDraft(current=>({...current,response_mode:mode,match_mode:mode==='grounded'?'smart':'contains',answer:mode==='refusal'&&!current.answer?'من درباره این موضوع اطلاعاتی ندارم.':current.answer}));
  const updateTriggers=(value:string)=>{const values=splitLines(value);setDraft(current=>({...current,question:values[0]||'',aliases:values.slice(1)}))};
  const updateAction=(index:number,key:keyof AssistantKnowledgeAction,value:string)=>setDraft(current=>{const actions=[...(current.actions||[])];actions[index]={...(actions[index]||{label:'مشاهده بخش مرتبط',path:'/'}),[key]:value};return {...current,actions}});
  const addAction=()=>setDraft(current=>({...current,actions:[...(current.actions||[]),{label:'مشاهده بخش مرتبط',path:'/'}].slice(0,3)}));
  const removeAction=(index:number)=>setDraft(current=>({...current,actions:(current.actions||[]).filter((_,i)=>i!==index)}));
  const selectionLabel='دانش دستیار سایت';
  const save=async()=>{if(!draft.question?.trim()||!draft.answer?.trim()){setMessage('حداقل یک جمله کاربر و پاسخ ربات را وارد کنید.');return}setSaving(true);try{await assistantAdminSave(draft,scope);setDraft(empty(scope));setMessage(`دانش برای ${selectionLabel} ذخیره${draft.status==='published'?' و منتشر':''} شد.`);await load()}catch(error){setMessage(String((error as Error)?.message||error))}finally{setSaving(false)}};
  const edit=(item:AssistantAdminItem)=>{setDraft({...item,original_question:item.original_question||item.question,aliases:[...(item.aliases||[])],keywords:[...(item.keywords||[])],actions:[...(item.actions||[])]});document.getElementById('assistant-editor')?.scrollIntoView({behavior:'smooth',block:'start'})};
  const parseQuick=async()=>{if(quick.trim().length<5){setMessage('دستور آموزش خیلی کوتاه است.');return}setParsing(true);try{const result=await assistantAdminParseInstruction(quick,scope);if(result.draft.needs_clarification){setMessage(result.draft.clarification_message);return}setDraft({...empty(scope),...result.draft,status:'published',is_active:true,created_by:'admin-panel'});setMessage('دستور فهمیده شد. پیش‌نویس زیر را بررسی و سپس ذخیره کنید.');document.getElementById('assistant-editor')?.scrollIntoView({behavior:'smooth',block:'start'})}catch(error){setMessage(String((error as Error)?.message||error))}finally{setParsing(false)}};
  const saveEnabled=async(enabled:boolean)=>{if(!data)return;const previous=data.settings,next={...data.settings,enabled};setData({...data,settings:next});try{const result=await assistantAdminSettings(next);setData(current=>current?{...current,settings:{...current.settings,...result.settings}}:current);announceAssistantSettings(enabled);setMessage(enabled?'دستیار فعال شد و دوباره در بالای سایت نمایش داده می‌شود.':'دستیار غیرفعال شد و دکمه آن از بالای سایت حذف می‌شود.')}catch(error){setData(current=>current?{...current,settings:previous}:current);setMessage(String((error as Error)?.message||error))}};
  const saveSettings=async()=>{if(!data)return;try{const result=await assistantAdminSettings(data.settings);setData(current=>current?{...current,settings:{...current.settings,...result.settings}}:current);announceAssistantSettings(data.settings.enabled===true);setMessage('متن‌ها و تنظیمات دستیار ذخیره شد.')}catch(error){setMessage(String((error as Error)?.message||error))}};
  const test=async()=>{if(testQuestion.trim().length<2)return;setTesting(true);try{setTestResult(await assistantAdminTestKnowledge(testQuestion,scope))}catch(error){setMessage(String((error as Error)?.message||error))}finally{setTesting(false)}};
  const testSingles=useMemo<Array<{scope:'public'|'admin';result:AssistantKnowledgeTestSingle}>>(()=>!testResult?[]:testResult.scope==='both'?[{scope:'public',result:testResult.results.public},{scope:'admin',result:testResult.results.admin}]:[{scope:(testResult.scope||(scope==='admin'?'admin':'public')),result:testResult} as {scope:'public'|'admin';result:AssistantKnowledgeTestSingle}],[testResult,scope]);
  const trainTestResult=()=>{const trusted=testSingles.find(item=>item.result.needs_training!==true)?.result.answer||testSingles.find(item=>item.result.answer&&!item.result.answer.includes('پیدا نشد'))?.result.answer||'';setDraft({...empty(scope),question:testQuestion,answer:trusted,status:'draft'});document.getElementById('assistant-editor')?.scrollIntoView({behavior:'smooth'})};
  const repairTelegram=async()=>{setTelegramBusy(true);try{const result=await assistantAdminTelegramRepair();setTelegram(result.status);setMessage(result.status.connected?'اتصال وب‌هوک، فرمان‌ها و دکمه‌های ربات تلگرام با موفقیت تنظیم شد.':'تنظیم انجام شد، اما اتصال هنوز کامل نیست.')}catch(error){setMessage(String((error as Error)?.message||error))}finally{setTelegramBusy(false)}};
  const exportKnowledge=async()=>{setExportBusy(true);try{const {blob,filename}=await assistantAdminExportKnowledge(),downloadUrl=URL.createObjectURL(blob),link=document.createElement('a');link.href=downloadUrl;link.download=filename;document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(downloadUrl),1000);setMessage('فایل بکاپ کامل دانش دستیار سایت آماده و دانلود شد.')}catch(error){setMessage(String((error as Error)?.message||error))}finally{setExportBusy(false)}};
  const emptyPendingEditor=():PendingEditor=>({answer:'',aliases:'',keywords:'',notice:'پاسخ فقط پس از نوشتن و تأیید شما منتشر می‌شود.',suggestedAnswer:'',suggestedNotice:'',grouped:0});
  const pendingEditor=(id:number):PendingEditor=>unansweredEditors[id]||emptyPendingEditor();
  const patchPending=(id:number,patch:Partial<PendingEditor>)=>setUnansweredEditors(current=>({...current,[id]:{...emptyPendingEditor(),...(current[id]||{}),...patch}}));
  const prepareUnanswered=async(item:any)=>{patchPending(item.id,{preparing:true});try{const result=await assistantAdminUnansweredDraft(item.id);setUnansweredEditors(current=>{const prior=current[item.id]||emptyPendingEditor();return {...current,[item.id]:{...prior,aliases:prior.aliases||result.draft.aliases.join('\n'),keywords:prior.keywords||result.draft.keywords.join('، '),notice:result.draft.owner_notice,suggestedAnswer:result.draft.suggested_answer||'',suggestedNotice:result.draft.suggested_answer_notice||'',grouped:result.draft.grouped_occurrences,preparing:false}}})}catch(error){patchPending(item.id,{preparing:false});setMessage(String((error as Error)?.message||error))}};
  const resolveUnanswered=async(item:any)=>{const editor=pendingEditor(item.id);if(editor.answer.trim().length<2){setMessage('پاسخ تأییدشده را برای این سؤال بنویسید.');return}patchPending(item.id,{saving:true});try{await assistantAdminResolveUnanswered(item.id,editor.answer,splitLines(editor.aliases),splitList(editor.keywords));setUnansweredEditors(current=>{const next={...current};delete next[item.id];return next});setOpenUnansweredId(null);setMessage('پاسخ شما همان لحظه به دانش دستیار اضافه و منتشر شد.');await load()}catch(error){patchPending(item.id,{saving:false});setMessage(String((error as Error)?.message||error))}};
  const archiveUnanswered=async(item:any)=>{try{await assistantAdminUnansweredStatus(item.id,'ignored');setOpenUnansweredId(null);setMessage('سؤال بایگانی شد؛ داده آن حذف نشده است.');await load()}catch(error){setMessage(String((error as Error)?.message||error))}};
  const clearAllUnanswered=async()=>{if(!clearUnanswered){setClearUnanswered(true);return}try{const result=await assistantAdminClearUnanswered();setClearUnanswered(false);setOpenUnansweredId(null);setUnansweredEditors({});setMessage(`${result.archived} سؤالِ در انتظار پاسخ بایگانی شد؛ هیچ داده‌ای حذف نشد.`);await load()}catch(error){setMessage(String((error as Error)?.message||error))}};
  const importContent=async()=>{const rows:any[]=[];for(const faq of Array.isArray(cfg.faqItems)?cfg.faqItems:[])if(faq?.question&&faq?.answer)rows.push({question:faq.question,answer:faq.answer,category:'سؤالات متداول',status:'draft',actions:[{path:'/faq',label:'مشاهده سؤالات متداول'}],created_by:'admin-import'});for(const tab of cfg.courseTabs||[])for(const course of tab.courses||[])if(course?.active!==false&&course?.title)rows.push({question:`دوره ${course.title} چیست؟`,answer:String(course.desc||course.description||'جزئیات دوره در صفحه دوره‌ها قرار دارد.'),category:'دوره‌ها',keywords:[tab.title,course.title].filter(Boolean),status:'draft',actions:[{path:'/courses',label:'مشاهده دوره‌ها'}],created_by:'admin-import'});try{const result=await assistantAdminImport(rows,scope),count=typeof result.imported==='number'?result.imported:Object.values(result.imported).reduce((sum,value)=>sum+value,0);setMessage(`${count} مورد برای ${selectionLabel} به‌صورت پیش‌نویس وارد شد.`);await load()}catch(error){setMessage(String((error as Error)?.message||error))}};
  if(loading)return <div style={{padding:24,color:T.mut}}>در حال بارگذاری دستیار…</div>;if(!data)return <div style={{padding:24,color:T.err}}>اطلاعات دستیار دریافت نشد.</div>;
  return <div data-testid="assistant-manager" className="zkam" style={vars}>
    {message&&<div role="status" className="zkam-message">{message}</div>}
    <div className="zkam-top">
      <section className="zkam-card zkam-status"><div><h3>{data.settings.enabled===true?'دستیار سایت فعال است':'دستیار سایت غیرفعال است'}</h3><p>با خاموش‌کردن، دکمه و پاسخ عمومی حذف می‌شود؛ این صفحه برای فعال‌سازی دوباره و ربات خصوصی تلگرام برای مدیریت دانش باقی می‌مانند.</p></div><label className="zkam-switch" aria-label="فعال یا غیرفعال کردن دستیار سایت"><input data-testid="assistant-enabled-toggle" type="checkbox" checked={data.settings.enabled===true} onChange={event=>saveEnabled(event.target.checked)}/><span/></label></section>
      <section className="zkam-card zkam-telegram"><div><h3><span className={`zkam-dot ${telegram?.connected?'ok':''}`}/>ربات تلگرام</h3><p>{telegram?.connected?`متصل${telegram.bot?.username?` به @${telegram.bot.username}`:''}`:telegram?.error||'در حال بررسی اتصال…'}{telegram?.webhook?.pending_updates?` · ${telegram.webhook.pending_updates} پیام در انتظار`:''}</p></div><button type="button" disabled={telegramBusy} onClick={repairTelegram}>{telegramBusy?'در حال اتصال…':telegram?.connected?'بازتنظیم و تست اتصال':'اتصال و تعمیر خودکار'}</button></section>
      <section className="zkam-card zkam-backup"><div><h3>📦 بکاپ کامل دانش</h3><p>تمام دانش دستیار صفحات عمومی این پروژه را در یک فایل Markdown دریافت کنید.</p></div><button data-testid="assistant-export-knowledge" type="button" disabled={exportBusy} onClick={exportKnowledge}>{exportBusy?'در حال تهیه فایل…':'دانلود بکاپ دانش'}</button></section>
    </div>
    <div className="zkam-grid3">{[['دانش منتشرشده دستیار سایت',publicPublished],['سؤال‌های بی‌پاسخ',data.unanswered.filter(item=>item.status==='pending').length]].map(([label,value])=><div className="zkam-stat" key={String(label)}><b>{value}</b><span>{label}</span></div>)}</div>

    <section className="zkam-card zkam-quick"><h3>✨ آموزش با یک جمله</h3><p>دقیقاً مثل ربات تلگرام، طبیعی بنویسید؛ چیزی خودکار منتشر نمی‌شود و ابتدا پیش‌نویس قابل بررسی می‌بینید.</p><textarea data-testid="assistant-quick-instruction" value={quick} onChange={event=>setQuick(event.target.value)} placeholder={'مثال: اگر کاربر گفت «قیمت مشاوره چقدر است؟» یا «هزینه مشاوره»، دقیقاً بگو «برای دیدن هزینه وارد فرم مشاوره شوید» و دکمه ثبت مشاوره را نمایش بده.'}/><button data-testid="assistant-parse-instruction" type="button" className="primary" disabled={parsing} onClick={parseQuick}>{parsing?'در حال فهمیدن دستور…':'فهمیدن دستور و ساخت پیش‌نویس'}</button></section>
    <section id="assistant-editor" className="zkam-card"><div className="zkam-row" style={{justifyContent:'space-between'}}><div><h3>{draft.id?'ویرایش دانش':'آموزش دانش جدید'}</h3><p>فقط دو بخش اول الزامی است: جمله‌های کاربر و پاسخ ربات.</p></div>{scope!=='admin'&&<button type="button" onClick={importContent}>ورود پیش‌نویس از محتوا و دوره‌ها{scope==='both'?' برای هر دو':''}</button>}</div>
      <div className="zkam-editor-grid">
        <label className="zkam-span2">کاربر ممکن است چه بگوید؟ <small>هر جمله مشابه را در یک خط جدا بنویسید.</small><textarea data-testid="assistant-triggers" value={triggersOf(draft)} onChange={event=>updateTriggers(event.target.value)} placeholder={'هزینه مشاوره چقدر است؟\nقیمت مشاوره\nمشاوره چنده؟'}/></label>
        <label className="zkam-span2">ربات چه بگوید؟<textarea data-testid="assistant-answer" value={String(draft.answer||'')} onChange={event=>set('answer',event.target.value)} placeholder="پاسخ تأییدشده را بنویسید…"/></label>
        <div className="zkam-span2"><label>شیوه پاسخ</label><div className="zkam-modes">{(Object.keys(modeCopy) as AssistantResponseMode[]).map(mode=><button type="button" key={mode} className={`zkam-mode ${draft.response_mode===mode?'active':''}`} onClick={()=>changeMode(mode)}>{modeCopy[mode].title}<small>{modeCopy[mode].desc}</small></button>)}</div></div>
        {scope!=='admin'&&<div className="zkam-span2"><div className="zkam-row" style={{justifyContent:'space-between'}}><label>دکمه‌های زیر پاسخ <small>اختیاری، حداکثر ۳ دکمه برای سایت</small></label>{(draft.actions||[]).length<3&&<button type="button" onClick={addAction}>+ افزودن دکمه</button>}</div>{(draft.actions||[]).map((action,index)=><div className="zkam-linkrow" key={index}><label>عنوان دکمه<input value={action.label} onChange={event=>updateAction(index,'label',event.target.value)}/></label><label>صفحه<select value={action.path} onChange={event=>updateAction(index,'path',event.target.value)}>{paths.map(([path,label])=><option key={path} value={path}>{label} — {path}</option>)}</select></label><button type="button" className="danger" onClick={()=>removeAction(index)}>حذف دکمه</button></div>)}</div>}
        {scope!=='public'&&<><label>تب مقصد پنل<select value={draft.target_tab||'dashboard'} onChange={event=>set('target_tab',event.target.value)}>{tabs.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>عنوان دکمه انتقال در پنل<input value={draft.action_label||''} onChange={event=>set('action_label',event.target.value)}/></label><label className="zkam-span2">متن بخشی که باید در پنل برجسته شود<input value={draft.target_focus||''} onChange={event=>set('target_focus',event.target.value)}/></label></>}
        <details className="zkam-span2"><summary>تنظیمات پیشرفته</summary><div className="zkam-editor-grid"><label>نوع تشخیص<select value={draft.match_mode||'smart'} onChange={event=>set('match_mode',event.target.value as AssistantMatchMode)}><option value="smart">هوشمند؛ جمله‌های مشابه</option><option value="contains">اگر عبارت داخل سؤال بود</option><option value="exact">فقط همان جمله دقیق</option></select></label><label>دسته‌بندی<input value={draft.category||''} onChange={event=>set('category',event.target.value)}/></label><label>کلمات کلیدی<input value={(draft.keywords||[]).join('، ')} onChange={event=>set('keywords',splitList(event.target.value))}/></label><label>اولویت<input type="number" min="-100" max="100" value={draft.priority||0} onChange={event=>set('priority',Number(event.target.value))}/></label>{scope!=='admin'&&<label className="zkam-span2">لینک منبع اختیاری<input value={draft.source_url||''} onChange={event=>set('source_url',event.target.value)}/></label>}</div></details>
      </div>
      <div className="zkam-actions"><label style={{flexDirection:'row',alignItems:'center'}}><input style={{width:'auto'}} type="checkbox" checked={draft.status==='published'} onChange={event=>set('status',event.target.checked?'published':'draft')}/> بلافاصله منتشر شود</label><label style={{flexDirection:'row',alignItems:'center'}}><input style={{width:'auto'}} type="checkbox" checked={draft.is_active!==false} onChange={event=>set('is_active',event.target.checked)}/> فعال باشد</label><button data-testid="assistant-save-knowledge" type="button" className="primary" disabled={saving} onClick={save}>{saving?'در حال ذخیره…':draft.id?'ذخیره ویرایش':'ذخیره دانش'}</button>{draft.id&&<button type="button" onClick={()=>setDraft(empty(scope))}>انصراف از ویرایش</button>}</div>
    </section>
    <section className="zkam-card"><h3>🧪 آزمایش قبل از استفاده</h3><p>سؤال را دقیقاً مثل کاربر بنویسید؛ پاسخ از مجموعه دانش مشترک دستیار سایت و محتوای زنده صفحات آموزش، مجوزها، تجربه والدین، نظرات و سؤالات متداول می‌آید.</p><div className="zkam-row"><input data-testid="assistant-test-question" style={{flex:1}} value={testQuestion} onChange={event=>setTestQuestion(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')test()}} placeholder="مثلاً: مشاوره چنده؟"/><button data-testid="assistant-test-knowledge" type="button" className="primary" disabled={testing||testQuestion.trim().length<2} onClick={test}>{testing?'در حال آزمایش…':scope==='both'?'آزمایش هر دو پاسخ':'آزمایش پاسخ'}</button></div>{testResult&&<div className="zkam-test-results">{testSingles.map(({scope:resultScope,result})=><div className="zkam-test-result" key={resultScope}><h4>{resultScope==='public'?'دانش کاربران سایت':'راهنمای پنل مدیریت'}</h4><b>{result.model}</b>{'\n'}{result.answer}{result.actions?.length?`\n\nدکمه‌ها: ${result.actions.map((item:any)=>item.label).join('، ')}`:''}<div className={`zkam-test-advice ${result.needs_training?'warn':'ok'}`}>{result.needs_training?'دانش مستقیم و مطمئنی برای این سؤال پیدا نشد؛ بهتر است پاسخ را آموزش دهید.':'این سؤال دانش مستقیم و قابل‌اتکا دارد.'}</div></div>)}{testSingles.some(item=>item.result.needs_training)&&<button data-testid="assistant-train-test-result" type="button" onClick={trainTestResult}>افزودن این سؤال به {selectionLabel}</button>}</div>}</section>
    <section className="zkam-card"><div className="zkam-row" style={{justifyContent:'space-between'}}><div><h3>فهرست {selectionLabel}</h3><p>{visible.length} مورد نمایش داده می‌شود.{scope==='both'?' موارد هم‌نام یک‌بار نمایش داده شده‌اند.':''}</p></div><input style={{maxWidth:300}} value={search} onChange={event=>setSearch(event.target.value)} placeholder="جست‌وجوی سؤال یا پاسخ…"/></div><div className="zkam-list">{visible.map(item=><article className="zkam-item" key={`${item.source_scope}-${item.id}`}><div className="zkam-item-head"><h4>{item.question}</h4><span className={`zkam-badge ${item.status==='published'&&item.is_active?'ok':'warn'}`}>{item.status==='published'&&item.is_active?'منتشر و فعال':'پیش‌نویس/خاموش'}</span></div>{scope==='both'&&<div className="zkam-scope-presence">{item.scope_presence?.includes('public')&&<span>سایت</span>}{item.scope_presence?.includes('admin')&&<span>پنل</span>}{item.scope_presence?.length===1&&<small>با ذخیره در «هر دو»، نسخه دیگر نیز ساخته می‌شود.</small>}</div>}<p>{item.answer}</p><small>{modeCopy[(item.response_mode||'grounded') as AssistantResponseMode]?.title||'پاسخ هوشمند'} · {(item.aliases||[]).length} جمله مشابه{scope!=='admin'&&(item.actions||[]).length?` · ${(item.actions||[]).length} دکمه`:''}</small><div className="zkam-actions"><button type="button" onClick={()=>edit(item)}>ویرایش</button><button type="button" onClick={async()=>{await assistantAdminSave({...item,status:item.status==='published'?'draft':'published'},scope);await load()}}>{item.status==='published'?'تبدیل به پیش‌نویس':'انتشار'}</button><button type="button" onClick={async()=>{await assistantAdminSave({...item,is_active:!item.is_active},scope);await load()}}>{item.is_active?'غیرفعال‌کردن':'فعال‌کردن'}</button><button type="button" className="danger" onClick={()=>setDeleteId(item.id)}>حذف</button></div>{deleteId===item.id&&<div className="zkam-delete"><b>{scope==='both'?'این دانش از هر دو دستیار حذف شود؟':'این دانش حذف شود؟'}</b><div className="zkam-actions"><button type="button" className="danger" onClick={async()=>{await assistantAdminDelete(item.id,scope,item);setDeleteId('');await load()}}>بله، حذف قطعی</button><button type="button" onClick={()=>setDeleteId('')}>انصراف</button></div></div>}</article>)}{!visible.length&&<p>دانشی در این بخش پیدا نشد.</p>}</div></section>
    {scope!=='admin'&&<section className="zkam-card zkam-unanswered">
      <div className="zkam-row" style={{justifyContent:'space-between'}}><div><h3>سؤال‌های بی‌پاسخ کاربران</h3><p>هر مورد را باز کنید، پاسخ تأییدشده خودتان را بنویسید و همان لحظه منتشر کنید. یارِ بررسی عبارت‌های هم‌معنی، کلمات کلیدی و در صورت امن‌بودن یک پیش‌نویس پاسخ پیشنهاد می‌کند؛ هیچ پاسخ تازه‌ای خودکار منتشر نمی‌شود.</p></div><div className="zkam-actions"><button data-testid="assistant-clear-unanswered" type="button" className={clearUnanswered?'danger':''} onClick={clearAllUnanswered}>{clearUnanswered?'تأیید بایگانی همه':'بایگانی همه سؤال‌ها'}</button>{clearUnanswered&&<button type="button" onClick={()=>setClearUnanswered(false)}>انصراف</button>}</div></div>
      {clearUnanswered&&<p className="zkam-unanswered-warning">فقط سؤال‌های در انتظار پاسخ همین سایت بایگانی می‌شوند و هیچ سطری حذف نمی‌شود.</p>}
      <div className="zkam-unanswered-list">{pendingUnanswered.length?pendingUnanswered.map(item=>{const editor=pendingEditor(item.id);return <details className="zkam-unanswered-item" key={item.id} open={openUnansweredId===item.id} onToggle={event=>setOpenUnansweredId(event.currentTarget.open?item.id:null)}>
        <summary><span><b>{item.question}</b><small>{item.occurrences} بار · {unansweredReason[item.detection_reason||'no_match']||'نیازمند بررسی'}</small></span><span aria-hidden="true">⌄</span></summary>
        <div className="zkam-unanswered-body"><p>{editor.grouped>item.occurrences?`${editor.grouped} بار در یک گروه هم‌معنی دیده شده است. `:''}{editor.notice}</p><div className="zkam-actions"><button type="button" disabled={editor.preparing||editor.saving} onClick={()=>prepareUnanswered(item)}>{editor.preparing?'در حال آماده‌سازی…':'دریافت پیشنهادهای یار بررسی'}</button><button type="button" className="danger" disabled={editor.saving} onClick={()=>archiveUnanswered(item)}>بایگانی این سؤال</button></div>{editor.suggestedNotice&&<div className="zkam-unanswered-suggestion"><b>پیش‌نویس پیشنهادی</b><p>{editor.suggestedNotice}</p>{editor.suggestedAnswer&&<><blockquote>{editor.suggestedAnswer}</blockquote><button type="button" onClick={()=>patchPending(item.id,{answer:editor.suggestedAnswer})}>قرار دادن پیش‌نویس در کادر پاسخ</button></>}</div>}
          <label>پاسخ تأییدشده شما<textarea data-testid={`assistant-unanswered-answer-${item.id}`} value={editor.answer} onChange={event=>patchPending(item.id,{answer:event.target.value})} placeholder="پاسخ خودتان را بنویسید؛ عین همین متن منتشر می‌شود."/></label>
          <label>عبارت‌های مشابه پیشنهادی <small>اختیاری؛ هرکدام در یک خط. قبل از انتشار قابل ویرایش‌اند.</small><textarea value={editor.aliases} onChange={event=>patchPending(item.id,{aliases:event.target.value})} placeholder="برای دیدن پیشنهادها دکمه بالا را بزنید."/></label>
          <label>کلمات کلیدی پیشنهادی <input value={editor.keywords} onChange={event=>patchPending(item.id,{keywords:event.target.value})} placeholder="اختیاری"/></label>
          <button data-testid={`assistant-resolve-unanswered-${item.id}`} type="button" className="primary" disabled={editor.saving} onClick={()=>resolveUnanswered(item)}>{editor.saving?'در حال انتشار…':'ذخیره پاسخ و انتشار فوری'}</button>
        </div>
      </details>}) : <p>موردی در انتظار پاسخ نیست.</p>}</div>
    </section>}
    <section className="zkam-card"><details><summary>متن‌های عمومی و تنظیمات تکمیلی دستیار</summary>{[['پیام خوش‌آمد','welcome_message'],['پاسخ وقتی اطلاعاتی ندارد','fallback_message'],['متن محدودیت و مسئولیت','disclaimer']].map(([label,key])=><label key={key}>{label}<textarea value={String((data.settings as any)[key]||'')} onChange={event=>setData(current=>current?{...current,settings:{...current.settings,[key]:event.target.value}}:current)}/></label>)}<label>اعلان پرتکرار بعد از چند بار تکرار؟<small>بین ۲ تا ۱۰۰؛ اعلان‌های بعدی در نقاط مهم دوباره ارسال می‌شوند.</small><input data-testid="assistant-frequent-threshold" type="number" min="2" max="100" value={data.settings.frequent_question_threshold||3} onChange={event=>setData(current=>current?{...current,settings:{...current.settings,frequent_question_threshold:Math.max(2,Math.min(100,Number(event.target.value)||3))}}:current)}/></label><button type="button" className="primary" onClick={saveSettings}>ذخیره متن‌ها و تنظیمات دستیار</button></details></section>
  </div>;
}
