import {useEffect,useMemo,useState} from 'react';
import type {DynamicRecord} from '../app/AppContext';
import {assistantAdminDelete,assistantAdminImport,assistantAdminList,assistantAdminSave,assistantAdminSettings,assistantAdminUnansweredStatus,type AssistantAdminData,type AssistantAdminItem,type AssistantKnowledgeScope} from '../lib/assistantAdminApi';

const tabs=[['dashboard','داشبورد'],['data','فرم‌ها و سفارشات'],['userQuestions','سؤالات مخاطبین'],['assistant','دستیار'],['reviews','نظرات'],['consultants','مشاوران'],['courses','دوره‌ها'],['featured','دوره‌های ویژه'],['tagged','دوره‌های تگ‌دار'],['products','محصولات'],['services','خدمات'],['trustbox','اعتمادساز'],['trust','جملات موفقیت'],['shipping','ارسال و پرداخت'],['content','محتوا'],['images','تصاویر'],['highlights','هایلایت'],['licenses','مجوزها'],['contacts','ارتباط'],['settings','تنظیمات'],['design','دیزاین'],['security','امنیت'],['analytics','آمار'],['errors','خطاها'],['trash','سطل بازیافت']];
const empty=(scope:AssistantKnowledgeScope):Partial<AssistantAdminItem>=>({question:'',answer:'',aliases:[],keywords:[],category:scope==='admin'?'مدیریت':'عمومی',link_url:'',link_label:'',source_url:'',target_tab:'dashboard',target_focus:'',action_label:'رفتن به بخش مرتبط',status:'draft',is_active:true,priority:0,created_by:'admin-panel'});
const arrayText=(value:unknown)=>Array.isArray(value)?value.join('، '):String(value||'');

export default function AssistantManager({T,S,cfg}:{T:DynamicRecord;S:DynamicRecord;cfg:DynamicRecord}){
 const [data,setData]=useState<AssistantAdminData|null>(null),[scope,setScope]=useState<AssistantKnowledgeScope>('public'),[draft,setDraft]=useState<Partial<AssistantAdminItem>>(empty('public')),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[search,setSearch]=useState('');
 const load=async()=>{setLoading(true);try{setData(await assistantAdminList())}catch(error){setMessage(String((error as Error)?.message||error))}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const items=scope==='admin'?(data?.adminKnowledge||[]):(data?.knowledge||[]);const visible=useMemo(()=>items.filter(item=>!search||`${item.question} ${item.answer} ${item.category}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const switchScope=(next:AssistantKnowledgeScope)=>{setScope(next);setDraft(empty(next));setSearch('');setMessage('')};
 const save=async()=>{if(!draft.question?.trim()||!draft.answer?.trim()){setMessage('سؤال و پاسخ الزامی است.');return}setSaving(true);try{await assistantAdminSave(draft,scope);setDraft(empty(scope));setMessage(`دانش ${scope==='admin'?'مدیریتی':'عمومی'} ذخیره شد.`);await load()}catch(error){setMessage(String((error as Error)?.message||error))}finally{setSaving(false)}};
 const importContent=async()=>{const rows:any[]=[];const faqs:any[]=[...(Array.isArray(cfg.faqItems)?cfg.faqItems:[])];for(const faq of faqs)if(faq?.question&&faq?.answer)rows.push({question:faq.question,answer:faq.answer,category:'سؤالات متداول',status:'draft',link_url:'/faq',link_label:'مشاهده سؤالات متداول',created_by:'admin-import'});for(const tab of cfg.courseTabs||[])for(const course of tab.courses||[])if(course?.active!==false&&course?.title)rows.push({question:`دوره ${course.title} چیست؟`,answer:String(course.desc||course.description||'جزئیات دوره در صفحه دوره‌ها قرار دارد.'),category:'دوره‌ها',keywords:[tab.title,course.title].filter(Boolean),status:'draft',link_url:'/courses',link_label:'مشاهده دوره‌ها',created_by:'admin-import'});try{const result=await assistantAdminImport(rows);setMessage(`${result.imported||0} مورد عمومی به‌صورت پیش‌نویس وارد شد.`);await load()}catch(error){setMessage(String((error as Error)?.message||error))}};
 const set=(key:keyof AssistantAdminItem,value:unknown)=>setDraft(current=>({...current,[key]:value}));
 const field=(label:string,key:keyof AssistantAdminItem,area=false)=><label style={{display:'flex',flexDirection:'column',fontSize:12,fontWeight:800,color:T.ttl,marginBottom:9}}>{label}{area?<textarea style={{...S.ta,marginTop:5,minHeight:key==='answer'?110:58}} value={String(draft[key]||'')} onChange={event=>set(key,event.target.value)}/>:<input style={{...S.inp,marginTop:5}} value={key==='aliases'||key==='keywords'?arrayText(draft[key]):String(draft[key]||'')} onChange={event=>set(key,event.target.value)}/>}</label>;
 if(loading)return <div style={{padding:24,color:T.mut}}>در حال بارگذاری دستیار…</div>;if(!data)return <div style={{padding:24,color:T.err}}>اطلاعات دستیار دریافت نشد.</div>;
 const publicPublished=data.knowledge.filter(item=>item.status==='published'&&item.is_active).length,adminPublished=data.adminKnowledge.filter(item=>item.status==='published'&&item.is_active).length;
 return <div data-testid="assistant-manager" style={{display:'flex',flexDirection:'column',gap:14}}>
  {message&&<div role="status" style={{padding:10,borderRadius:12,background:T.soft,color:T.acc,fontSize:12,fontWeight:800}}>{message}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:9}}>{[['دانش عمومی منتشرشده',publicPublished],['دانش مدیریتی منتشرشده',adminPublished],['سؤال‌های بدون پاسخ',data.unanswered.filter(item=>item.status==='pending').length]].map(([label,value])=><div key={String(label)} style={{padding:12,border:`1px solid ${T.brd}`,borderRadius:14,background:T.card,textAlign:'center'}}><b style={{display:'block',fontSize:21,color:T.acc}}>{value}</b><span style={{fontSize:11,color:T.mut}}>{label}</span></div>)}</div>
  <div role="tablist" aria-label="نوع دانش" style={{display:'flex',gap:7}}><button type="button" role="tab" aria-selected={scope==='public'} style={scope==='public'?S.btn:S.btnGhost} onClick={()=>switchScope('public')}>دانش عمومی سایت</button><button type="button" role="tab" aria-selected={scope==='admin'} style={scope==='admin'?S.btn:S.btnGhost} onClick={()=>switchScope('admin')}>راهنمای پنل مدیریت</button></div>
  <section style={{padding:14,border:`1px solid ${T.brd}`,borderRadius:16,background:T.card}}><h3 style={{margin:'0 0 10px',color:T.ttl}}>تنظیمات دستیار عمومی</h3><label style={{display:'flex',gap:7,alignItems:'center',marginBottom:10,fontSize:12,fontWeight:800}}><input type="checkbox" checked={data.settings.enabled!==false} onChange={event=>setData(current=>current?{...current,settings:{...current.settings,enabled:event.target.checked}}:current)}/> نمایش دستیار در سایت</label>{[['پیام خوش‌آمد','welcome_message'],['پاسخ سؤال نامرتبط','fallback_message'],['پاسخ درخواست مدیریتی در سایت','admin_block_message'],['متن محدودیت و مسئولیت','disclaimer']].map(([label,key])=><label key={key} style={{display:'flex',flexDirection:'column',fontSize:12,fontWeight:800,color:T.ttl,marginBottom:8}}>{label}<textarea style={{...S.ta,minHeight:58,marginTop:5}} value={String((data.settings as any)[key]||'')} onChange={event=>setData(current=>current?{...current,settings:{...current.settings,[key]:event.target.value}}:current)}/></label>)}<button type="button" style={S.btn} onClick={async()=>{try{await assistantAdminSettings(data.settings);setMessage('تنظیمات دستیار ذخیره شد.')}catch(error){setMessage(String((error as Error).message||error))}}}>ذخیره تنظیمات دستیار</button></section>
  <section style={{padding:14,border:`1px solid ${T.brd}`,borderRadius:16,background:T.card}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',marginBottom:10,flexWrap:'wrap'}}><h3 style={{margin:0,color:T.ttl}}>{draft.id?'ویرایش':'افزودن'} دانش {scope==='admin'?'مدیریتی':'عمومی'}</h3>{scope==='public'&&<button type="button" style={S.btnGhost} onClick={importContent}>ورود پیش‌نویس از محتوا و دوره‌ها</button>}</div>{field('سؤال اصلی','question',true)}{field('پاسخ تأییدشده','answer',true)}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8}}>{field('عبارت‌های مشابه — با ویرگول','aliases')}{field('کلمات کلیدی — با ویرگول','keywords')}{field('دسته‌بندی','category')}{scope==='public'?<>{field('مسیر دکمه عمومی','link_url')}{field('عنوان دکمه','link_label')}{field('لینک منبع','source_url')}</>:<><label style={{display:'flex',flexDirection:'column',fontSize:12,fontWeight:800,color:T.ttl,marginBottom:9}}>تب مقصد<select style={{...S.inp,marginTop:5}} value={draft.target_tab||'dashboard'} onChange={event=>set('target_tab',event.target.value)}>{tabs.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{field('متن بخش دقیق برای تمرکز','target_focus')}{field('عنوان دکمه انتقال','action_label')}</>}</div><div style={{display:'flex',gap:9,alignItems:'center',flexWrap:'wrap'}}><select style={S.inp} value={draft.status||'draft'} onChange={event=>set('status',event.target.value)}><option value="draft">پیش‌نویس</option><option value="published">منتشرشده</option></select><label style={{fontSize:12}}>اولویت <input type="number" min="-100" max="100" style={{...S.inp,width:90}} value={draft.priority||0} onChange={event=>set('priority',Number(event.target.value))}/></label><button type="button" disabled={saving} style={{...S.btn,flex:1}} onClick={save}>{saving?'در حال ذخیره…':'ذخیره دانش'}</button>{draft.id&&<button type="button" style={S.btnGhost} onClick={()=>setDraft(empty(scope))}>انصراف</button>}</div></section>
  <section style={{padding:14,border:`1px solid ${T.brd}`,borderRadius:16,background:T.card}}><div style={{display:'flex',justifyContent:'space-between',gap:8,marginBottom:10,flexWrap:'wrap'}}><h3 style={{margin:0,color:T.ttl}}>فهرست دانش {scope==='admin'?'مدیریتی':'عمومی'}</h3><input style={{...S.inp,maxWidth:300}} value={search} onChange={event=>setSearch(event.target.value)} placeholder="جست‌وجو…"/></div><div style={{display:'flex',flexDirection:'column',gap:8}}>{visible.map(item=><article key={item.id} style={{padding:11,border:`1px solid ${T.brd}`,borderRadius:13,background:T.soft}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b style={{fontSize:12.5,color:T.ttl}}>{item.question}</b><span style={{fontSize:10,color:item.status==='published'?T.ok:T.warn}}>{item.status==='published'?'منتشر':'پیش‌نویس'}</span></div><p style={{fontSize:12.5,color:T.txt,lineHeight:1.9,margin:'6px 0'}}>{item.answer.slice(0,300)}{item.answer.length>300?'…':''}</p>{scope==='admin'&&<small style={{color:T.mut}}>مقصد: {item.target_tab} {item.target_focus?`· ${item.target_focus}`:''}</small>}<div style={{display:'flex',gap:6,marginTop:8}}><button type="button" style={S.btnGhost} onClick={()=>setDraft({...item,aliases:[...(item.aliases||[])],keywords:[...(item.keywords||[])]})}>ویرایش</button><button type="button" style={{...S.btnGhost,color:T.err}} onClick={async()=>{if(confirm('این مورد حذف شود؟')){await assistantAdminDelete(item.id,scope);await load()}}}>حذف</button></div></article>)}</div></section>
  {scope==='public'&&<section style={{padding:14,border:`1px solid ${T.brd}`,borderRadius:16,background:T.card}}><h3 style={{margin:'0 0 10px',color:T.ttl}}>سؤال‌های بدون پاسخ</h3>{data.unanswered.length?data.unanswered.map(item=><div key={item.id} style={{display:'flex',gap:8,alignItems:'center',padding:'9px 0',borderBottom:`1px solid ${T.brd}`}}><span style={{flex:1,fontSize:12,color:T.txt}}>{item.question} <small style={{color:T.mut}}>({item.occurrences} بار)</small></span><button type="button" style={S.btnGhost} onClick={()=>{setDraft({...empty('public'),question:item.question});window.scrollTo({top:0,behavior:'smooth'})}}>ساخت پاسخ</button><select style={S.inp} value={item.status} onChange={async event=>{await assistantAdminUnansweredStatus(item.id,event.target.value as any);await load()}}><option value="pending">در انتظار</option><option value="resolved">حل‌شده</option><option value="ignored">نادیده</option></select></div>):<p style={{fontSize:12,color:T.mut}}>موردی وجود ندارد.</p>}</section>}
 </div>;
}
