-- Free, owner-curated assistant pilot for Zeynalikid.
-- No existing submission, setting, or Storage object is modified or deleted.
begin;
create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

create table if not exists public.assistant_knowledge(
 id uuid primary key default gen_random_uuid(),
 question text not null check(char_length(question) between 2 and 500),
 answer text not null check(char_length(answer) between 2 and 6000),
 aliases text[] not null default '{}',
 keywords text[] not null default '{}',
 category text not null default 'عمومی',
 link_url text,
 link_label text,
 source_url text,
 status text not null default 'draft' check(status in('draft','published')),
 is_active boolean not null default true,
 priority integer not null default 0 check(priority between -100 and 100),
 created_by text not null default 'admin-panel',
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.assistant_settings(
 key text primary key default 'default',
 enabled boolean not null default true,
 welcome_message text not null default 'سلام! سؤال خود را درباره دوره‌ها، خدمات و محتوای زینالیکید بپرسید.',
 fallback_message text not null default 'پاسخ تأییدشده‌ای برای این سؤال پیدا نکردم. می‌توانید فرم مشاوره را تکمیل کنید یا با پشتیبانی تماس بگیرید.',
 disclaimer text not null default 'این دستیار راهنمای عمومی است و جایگزین مشاوره یا پزشک نیست',
 updated_at timestamptz not null default now()
);
create table if not exists public.assistant_unanswered(
 id bigint generated by default as identity primary key,
 question text not null,
 question_normalized text not null unique,
 page_path text,
 occurrences integer not null default 1,
 status text not null default 'pending' check(status in('pending','resolved','ignored')),
 first_seen_at timestamptz not null default now(),
 last_seen_at timestamptz not null default now()
);
create table if not exists public.assistant_feedback(
 id bigint generated by default as identity primary key,
 knowledge_id uuid not null references public.assistant_knowledge(id) on delete cascade,
 helpful boolean not null,
 created_at timestamptz not null default now()
);
create table if not exists public.assistant_bot_states(
 chat_id text primary key,
 step text not null,
 draft jsonb not null default '{}',
 updated_at timestamptz not null default now()
);

insert into public.assistant_settings(key) values('default') on conflict(key) do nothing;
create index if not exists assistant_knowledge_question_trgm_idx on public.assistant_knowledge using gin(lower(question) gin_trgm_ops);
create index if not exists assistant_knowledge_keywords_idx on public.assistant_knowledge using gin(keywords);
create index if not exists assistant_knowledge_public_idx on public.assistant_knowledge(priority desc,updated_at desc) where status='published' and is_active=true;
create index if not exists assistant_unanswered_status_idx on public.assistant_unanswered(status,occurrences desc,last_seen_at desc);
create index if not exists assistant_feedback_knowledge_idx on public.assistant_feedback(knowledge_id,created_at desc);

drop trigger if exists assistant_knowledge_updated_at on public.assistant_knowledge;
create trigger assistant_knowledge_updated_at before update on public.assistant_knowledge for each row execute function public.zkid_set_updated_at();
drop trigger if exists assistant_settings_updated_at on public.assistant_settings;
create trigger assistant_settings_updated_at before update on public.assistant_settings for each row execute function public.zkid_set_updated_at();

alter table public.assistant_knowledge enable row level security;
alter table public.assistant_settings enable row level security;
alter table public.assistant_unanswered enable row level security;
alter table public.assistant_feedback enable row level security;
alter table public.assistant_bot_states enable row level security;
revoke all on public.assistant_knowledge,public.assistant_settings,public.assistant_unanswered,public.assistant_feedback,public.assistant_bot_states from public,anon,authenticated;
grant select,insert,update,delete on public.assistant_knowledge,public.assistant_settings,public.assistant_unanswered,public.assistant_feedback,public.assistant_bot_states to service_role;
grant usage,select on sequence public.assistant_unanswered_id_seq,public.assistant_feedback_id_seq to service_role;

drop policy if exists assistant_browser_deny on public.assistant_knowledge;
create policy assistant_browser_deny on public.assistant_knowledge for all to anon,authenticated using(false) with check(false);
drop policy if exists assistant_settings_browser_deny on public.assistant_settings;
create policy assistant_settings_browser_deny on public.assistant_settings for all to anon,authenticated using(false) with check(false);
drop policy if exists assistant_unanswered_browser_deny on public.assistant_unanswered;
create policy assistant_unanswered_browser_deny on public.assistant_unanswered for all to anon,authenticated using(false) with check(false);
drop policy if exists assistant_feedback_browser_deny on public.assistant_feedback;
create policy assistant_feedback_browser_deny on public.assistant_feedback for all to anon,authenticated using(false) with check(false);
drop policy if exists assistant_bot_states_browser_deny on public.assistant_bot_states;
create policy assistant_bot_states_browser_deny on public.assistant_bot_states for all to anon,authenticated using(false) with check(false);
commit;
