-- Scoped generative assistant for زینالیکید.
-- Additive only: no submissions, settings content, or Storage objects are removed.
begin;
create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

create or replace function public.assistant_set_updated_at() returns trigger
language plpgsql set search_path=public,pg_temp as $$begin new.updated_at=now();return new;end$$;

create table if not exists public.assistant_knowledge(
 id uuid primary key default gen_random_uuid(), question text not null check(char_length(question) between 2 and 500), answer text not null check(char_length(answer) between 2 and 6000), aliases text[] not null default '{}', keywords text[] not null default '{}', category text not null default 'عمومی', link_url text, link_label text, source_url text, status text not null default 'draft' check(status in('draft','published')), is_active boolean not null default true, priority integer not null default 0 check(priority between -100 and 100), created_by text not null default 'admin-panel', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.assistant_settings(
 key text primary key default 'default', enabled boolean not null default true, welcome_message text not null default 'سلام! سؤال خود را درباره خدمات و بخش‌های عمومی زینالیکید بپرسید.', fallback_message text not null default 'در مورد این سؤال اطلاعاتی ندارم. می‌توانم درباره ثبت مشاوره، پیگیری درخواست، دوره‌ها، محصولات و بخش‌های عمومی زینالیکید راهنمایی‌تان کنم.', disclaimer text not null default 'این دستیار راهنمای عمومی است و جایگزین پزشک یا مشاور تخصصی نیست.', updated_at timestamptz not null default now()
);
alter table public.assistant_settings add column if not exists suggested_questions jsonb not null default '[]'::jsonb;
alter table public.assistant_settings add column if not exists admin_block_message text not null default 'من درباره تنظیمات و امکانات مدیریتی سایت اطلاعاتی ارائه نمی‌دهم. می‌توانم درباره خدمات عمومی، دوره‌ها، ثبت مشاوره و پیگیری درخواست‌ها راهنمایی‌تان کنم.';
create table if not exists public.assistant_unanswered(id bigint generated by default as identity primary key,question text not null,question_normalized text not null unique,page_path text,occurrences integer not null default 1,status text not null default 'pending' check(status in('pending','resolved','ignored')),first_seen_at timestamptz not null default now(),last_seen_at timestamptz not null default now());
create table if not exists public.assistant_feedback(id bigint generated by default as identity primary key,knowledge_id uuid not null references public.assistant_knowledge(id) on delete cascade,helpful boolean not null,created_at timestamptz not null default now());
create table if not exists public.assistant_bot_states(chat_id text primary key,step text not null,draft jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.assistant_admin_knowledge(
 id uuid primary key default gen_random_uuid(), question text not null check(char_length(question) between 2 and 500), answer text not null check(char_length(answer) between 2 and 6000), aliases text[] not null default '{}', keywords text[] not null default '{}', category text not null default 'مدیریت', status text not null default 'draft' check(status in('draft','published')), is_active boolean not null default true, priority integer not null default 0 check(priority between -100 and 100), created_by text not null default 'admin-panel', target_tab text not null default 'dashboard', target_focus text not null default '', action_label text not null default 'رفتن به بخش مرتبط', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create unique index if not exists assistant_knowledge_question_unique on public.assistant_knowledge(lower(question));
create unique index if not exists assistant_admin_knowledge_question_unique on public.assistant_admin_knowledge(lower(question));

insert into public.assistant_settings(key) values('default') on conflict(key) do nothing;
update public.assistant_settings set
 welcome_message='سلام! درباره خدمات، دوره‌ها، ثبت مشاوره، پیگیری و بخش‌های عمومی زینالیکید از من بپرسید.',
 fallback_message='در مورد سؤالی که پرسیدید اطلاعاتی ندارم. می‌توانم درباره ثبت مشاوره، پیگیری درخواست، دوره‌ها، محصولات و بخش‌های عمومی زینالیکید راهنمایی‌تان کنم.',
 admin_block_message='من درباره تنظیمات و امکانات مدیریتی سایت اطلاعاتی ارائه نمی‌دهم. می‌توانم درباره خدمات عمومی، دوره‌ها، ثبت مشاوره و پیگیری درخواست‌ها راهنمایی‌تان کنم.',
 suggested_questions=jsonb_build_array(
  jsonb_build_object('question','چطور درخواست مشاوره ثبت کنم؟','label','ثبت مشاوره','path','/consultation'),
  jsonb_build_object('question','چطور درخواست خودم را پیگیری کنم؟','label','پیگیری درخواست','path','/track'),
  jsonb_build_object('question','دوره‌ها را از کجا ببینم؟','label','مشاهده دوره‌ها','path','/courses'),
  jsonb_build_object('question','چطور با شما تماس بگیرم؟','label','راه‌های ارتباطی','path','/contact')
 ) where key='default';

insert into public.assistant_knowledge(question,answer,aliases,keywords,category,link_url,link_label,status,is_active,priority,created_by) values
 ('چطور درخواست مشاوره ثبت کنم؟','برای ثبت درخواست مشاوره وارد فرم مشاوره شوید، اطلاعات لازم را تکمیل کنید و پس از ثبت کد پیگیری را نگه دارید.',array[]::text[],array['راهنمای سایت']::text[],'راهنمای سایت','/consultation','ورود به فرم مشاوره','published',true,20,'migration-seed'),
 ('چطور درخواست خودم را پیگیری کنم؟','برای پیگیری، وارد صفحه پیگیری شوید و کد پیگیری و اطلاعات خواسته‌شده را وارد کنید.',array[]::text[],array['راهنمای سایت']::text[],'راهنمای سایت','/track','پیگیری درخواست','published',true,20,'migration-seed'),
 ('دوره‌ها را از کجا ببینم؟','دوره‌های فعال و توضیحات آن‌ها در صفحه دوره‌ها قرار دارند.',array[]::text[],array['دوره‌ها']::text[],'دوره‌ها','/courses','مشاهده دوره‌ها','published',true,20,'migration-seed'),
 ('محصولات را از کجا ببینم؟','محصولات فعال در صفحه محصولات نمایش داده می‌شوند.',array[]::text[],array['محصولات']::text[],'محصولات','/products','مشاهده محصولات','published',true,20,'migration-seed'),
 ('محتوای آموزشی کجاست؟','مطالب و محتوای آموزشی منتشرشده در صفحه آموزش‌ها در دسترس است.',array[]::text[],array['آموزش']::text[],'آموزش','/education','مشاهده آموزش‌ها','published',true,20,'migration-seed'),
 ('سؤالات متداول را کجا ببینم؟','پاسخ پرسش‌های رایج در صفحه سؤالات متداول قرار دارد.',array[]::text[],array['راهنمای سایت']::text[],'راهنمای سایت','/faq','مشاهده سؤالات متداول','published',true,20,'migration-seed'),
 ('چطور با شما تماس بگیرم؟','راه‌های ارتباطی رسمی در صفحه ارتباط با ما نمایش داده می‌شوند.',array[]::text[],array['ارتباط']::text[],'ارتباط','/contact','راه‌های ارتباطی','published',true,20,'migration-seed'),
 ('درباره مجموعه کجا بخوانم؟','اطلاعات معرفی مجموعه در صفحه درباره ما قرار دارد.',array[]::text[],array['معرفی']::text[],'معرفی','/about','درباره ما','published',true,20,'migration-seed'),
 ('حریم خصوصی را کجا بخوانم؟','توضیحات نحوه استفاده و حفاظت از داده‌ها در صفحه حریم خصوصی قرار دارد.',array[]::text[],array['حقوقی']::text[],'حقوقی','/privacy','حریم خصوصی','published',true,20,'migration-seed')
on conflict do nothing;
insert into public.assistant_admin_knowledge(question,answer,aliases,keywords,category,status,is_active,priority,created_by,target_tab,target_focus,action_label) values
 ('چطور وضعیت کلی سایت را ببینم؟','برای مشاهده نمای کلی ثبت‌ها، سفارش‌ها و فعالیت‌های اخیر وارد داشبورد شوید.',array[]::text[],array['داشبورد']::text[],'داشبورد','published',true,20,'migration-seed','dashboard','نمای کلی','رفتن به داشبورد'),
 ('فرم‌ها و سفارش‌ها را از کجا مدیریت کنم؟','در بخش فرم‌ها و سفارشات می‌توانید درخواست‌های مشاوره و ثبت‌نام دوره را جست‌وجو، فیلتر و بررسی کنید.',array[]::text[],array['فرم‌ها']::text[],'فرم‌ها','published',true,20,'migration-seed','data','فرم‌ها و سفارشات','رفتن به فرم‌ها و سفارشات'),
 ('سؤال‌های مخاطبان را کجا ببینم؟','بخش سوالات مخاطبین برای مشاهده و مدیریت سؤال‌هایی است که کاربران از فرم «سؤال دارم» ارسال کرده‌اند.',array[]::text[],array['مخاطبان']::text[],'مخاطبان','published',true,20,'migration-seed','userQuestions','سوالات مخاطبین','رفتن به سؤال‌های مخاطبان'),
 ('دانش دستیار را چطور مدیریت کنم؟','از بخش دستیار می‌توانید دانش عمومی و مدیریتی را به‌صورت پیش‌نویس اضافه، بررسی و منتشر کنید.',array[]::text[],array['دستیار']::text[],'دستیار','published',true,20,'migration-seed','assistant','مدیریت دانش','رفتن به مدیریت دستیار'),
 ('نظرات کاربران را کجا مدیریت کنم؟','برای مشاهده، تأیید و مدیریت نظرات کاربران وارد بخش نظرات کاربران شوید.',array[]::text[],array['نظرات']::text[],'نظرات','published',true,20,'migration-seed','reviews','نظرات کاربران','رفتن به نظرات'),
 ('چطور مشاور یا لینک ارجاع را مدیریت کنم؟','از بخش مشاورین و لینک‌های ارجاع می‌توانید مشخصات مشاور، کد کوتاه و مسیرهای ارجاع را مدیریت کنید.',array[]::text[],array['ارجاع']::text[],'ارجاع','published',true,20,'migration-seed','consultants','مشاورین و لینک‌های ارجاع','رفتن به مشاوران'),
 ('چطور یک دوره اضافه یا ویرایش کنم؟','در بخش دوره‌ها تب موردنظر را باز کنید و دوره را اضافه یا ویرایش کنید؛ سپس تغییرات را ذخیره کنید.',array[]::text[],array['دوره‌ها']::text[],'دوره‌ها','published',true,20,'migration-seed','courses','دوره‌ها','رفتن به دوره‌ها'),
 ('دوره‌های ویژه صفحه اصلی را کجا تنظیم کنم؟','بخش دوره‌های ویژه برای انتخاب و تنظیم دوره‌هایی است که به‌صورت ویژه نمایش داده می‌شوند.',array[]::text[],array['دوره‌ها']::text[],'دوره‌ها','published',true,20,'migration-seed','featured','دوره‌های ویژه','رفتن به دوره‌های ویژه'),
 ('دوره‌های تگ‌دار را از کجا تنظیم کنم؟','برای مدیریت دوره‌هایی که با تگ‌های مشخص نمایش داده می‌شوند وارد بخش دوره‌های تگ‌دار شوید.',array[]::text[],array['دوره‌ها']::text[],'دوره‌ها','published',true,20,'migration-seed','tagged','دوره‌های تگ‌دار','رفتن به دوره‌های تگ‌دار'),
 ('محصولات فروشگاه را چطور مدیریت کنم؟','از بخش محصولات می‌توانید محصول جدید اضافه کنید یا مشخصات، نمایش و ترتیب محصولات را تغییر دهید.',array[]::text[],array['محصولات']::text[],'محصولات','published',true,20,'migration-seed','products','محصولات','رفتن به محصولات'),
 ('خدمات سایت را از کجا ویرایش کنم؟','در بخش خدمات می‌توانید آیتم‌های خدمات و نحوه نمایش لیستی یا کاروسل را مدیریت کنید.',array[]::text[],array['خدمات']::text[],'خدمات','published',true,20,'migration-seed','services','مدیریت لیست خدمات','رفتن به خدمات'),
 ('جملات اعتمادساز را کجا تغییر بدهم؟','برای مدیریت متن‌های اعتمادساز صفحه اصلی وارد بخش جملات اعتمادساز شوید.',array[]::text[],array['محتوا']::text[],'محتوا','published',true,20,'migration-seed','trustbox','جملات اعتمادساز','رفتن به جملات اعتمادساز'),
 ('جملات صفحه موفقیت را از کجا تغییر بدهم؟','بخش جملات صفحه موفقیت برای ویرایش پیام‌های نمایش‌داده‌شده پس از ثبت فرم‌ها و سفارش‌هاست.',array[]::text[],array['محتوا']::text[],'محتوا','published',true,20,'migration-seed','trust','جملات صفحه موفقیت','رفتن به جملات موفقیت'),
 ('اطلاعات بانک و ارسال را کجا تنظیم کنم؟','در بخش ارسال و پرداخت می‌توانید روش‌های ارسال، حساب‌های بانکی و تنظیمات مرتبط با پرداخت را مدیریت کنید.',array[]::text[],array['پرداخت']::text[],'پرداخت','published',true,20,'migration-seed','shipping','ارسال و پرداخت','رفتن به ارسال و پرداخت'),
 ('متن صفحات را از کجا تغییر بدهم؟','از بخش محتوا و صفحات می‌توانید متن‌ها، سؤالات متداول و محتوای صفحات عمومی را ویرایش و ذخیره کنید.',array[]::text[],array['محتوا']::text[],'محتوا','published',true,20,'migration-seed','content','محتوا و صفحات','رفتن به محتوا و صفحات'),
 ('تصاویر سایت را کجا مدیریت کنم؟','برای مدیریت تصاویر صفحه اصلی و فرم‌ها وارد بخش تصاویر شوید.',array[]::text[],array['رسانه']::text[],'رسانه','published',true,20,'migration-seed','images','تصاویر','رفتن به تصاویر'),
 ('هایلایت‌ها را چطور مدیریت کنم؟','در بخش هایلایت می‌توانید دسته‌ها و اسلایدهای هایلایت را اضافه، مرتب یا ویرایش کنید.',array[]::text[],array['رسانه']::text[],'رسانه','published',true,20,'migration-seed','highlights','هایلایت','رفتن به هایلایت‌ها'),
 ('مجوزها و گواهی‌ها را کجا قرار بدهم؟','از بخش مجوزها می‌توانید تصاویر و اطلاعات مجوزها و گواهی‌ها را مدیریت کنید.',array[]::text[],array['محتوا']::text[],'محتوا','published',true,20,'migration-seed','licenses','مجوزها','رفتن به مجوزها'),
 ('شماره تماس و شبکه‌های اجتماعی را کجا تغییر بدهم؟','برای ویرایش شماره‌ها، شبکه‌های اجتماعی و راه‌های ارتباطی وارد بخش راه‌های ارتباطی شوید.',array[]::text[],array['ارتباط']::text[],'ارتباط','published',true,20,'migration-seed','contacts','راه‌های ارتباطی','رفتن به راه‌های ارتباطی'),
 ('موضوع جدید به فرم مشاوره چطور اضافه کنم؟','از بخش تنظیمات، تنظیمات فرم مشاوره و فهرست موضوعات را پیدا کنید؛ موضوع جدید را اضافه و تغییرات را ذخیره کنید.',array[]::text[],array['تنظیمات']::text[],'تنظیمات','published',true,20,'migration-seed','settings','موضوع','رفتن به تنظیمات فرم'),
 ('تنظیمات فرم‌ها را کجا تغییر بدهم؟','در بخش تنظیمات می‌توانید فیلدها، متن‌ها و رفتار فرم‌های سایت را مدیریت کنید.',array[]::text[],array['تنظیمات']::text[],'تنظیمات','published',true,20,'migration-seed','settings','پیکربندی فرم‌ها','رفتن به تنظیمات'),
 ('دیزاین و تم سایت را چطور تغییر بدهم؟','از بخش مدیریت دیزاین، دیزاین فعال و تنظیمات ظاهری بخش‌های سایت را تغییر دهید و نتیجه را بررسی کنید.',array[]::text[],array['دیزاین']::text[],'دیزاین','published',true,20,'migration-seed','design','مدیریت دیزاین','رفتن به مدیریت دیزاین'),
 ('چطور رمز پنل مدیریت را تغییر بدهم؟','از بخش امنیت، قسمت تغییر اطلاعات ورود را باز کنید، رمز فعلی و رمز جدید حداقل ۱۲ کاراکتری را وارد و ذخیره کنید. پس از تغییر باید دوباره وارد شوید.',array[]::text[],array['امنیت']::text[],'امنیت','published',true,20,'migration-seed','security','تغییر اطلاعات ورود','رفتن به امنیت'),
 ('نشست‌ها و دستگاه‌های مدیر را کجا ببینم؟','در بخش امنیت می‌توانید دستگاه‌ها و نشست‌های مدیریتی را مشاهده و در صورت نیاز لغو کنید.',array[]::text[],array['امنیت']::text[],'امنیت','published',true,20,'migration-seed','security','دستگاه‌های فعال','رفتن به دستگاه‌ها'),
 ('آمار بازدید سایت را کجا ببینم؟','بخش آمار بازدید، اطلاعات بازدید صفحات را به تفکیک زمان نمایش می‌دهد.',array[]::text[],array['آمار']::text[],'آمار','published',true,20,'migration-seed','analytics','آمار بازدید','رفتن به آمار بازدید'),
 ('خطاهای سیستم را کجا بررسی کنم؟','برای بررسی خطاهای ثبت‌شده و وضعیت فنی وارد بخش خطاهای سیستم شوید.',array[]::text[],array['فنی']::text[],'فنی','published',true,20,'migration-seed','errors','خطاهای سیستم','رفتن به خطاهای سیستم'),
 ('موارد حذف‌شده را چطور بازیابی کنم؟','از بخش سطل بازیافت می‌توانید موارد حذف‌شده قابل بازیابی را مشاهده و در صورت نیاز بازگردانی کنید.',array[]::text[],array['بازیابی']::text[],'بازیابی','published',true,20,'migration-seed','trash','سطل بازیافت','رفتن به سطل بازیافت')
on conflict do nothing;

create unique index if not exists assistant_admin_knowledge_question_unique on public.assistant_admin_knowledge(lower(question));
create index if not exists assistant_knowledge_question_trgm_idx on public.assistant_knowledge using gin(lower(question) extensions.gin_trgm_ops);
create index if not exists assistant_knowledge_public_idx on public.assistant_knowledge(priority desc,updated_at desc) where status='published' and is_active=true;
create index if not exists assistant_admin_knowledge_public_idx on public.assistant_admin_knowledge(priority desc,updated_at desc) where status='published' and is_active=true;
create index if not exists assistant_admin_knowledge_question_trgm_idx on public.assistant_admin_knowledge using gin(lower(question) extensions.gin_trgm_ops);
create index if not exists assistant_unanswered_status_idx on public.assistant_unanswered(status,occurrences desc,last_seen_at desc);

drop trigger if exists assistant_knowledge_updated_at on public.assistant_knowledge;
create trigger assistant_knowledge_updated_at before update on public.assistant_knowledge for each row execute function public.assistant_set_updated_at();
drop trigger if exists assistant_settings_updated_at on public.assistant_settings;
create trigger assistant_settings_updated_at before update on public.assistant_settings for each row execute function public.assistant_set_updated_at();
drop trigger if exists assistant_admin_knowledge_updated_at on public.assistant_admin_knowledge;
create trigger assistant_admin_knowledge_updated_at before update on public.assistant_admin_knowledge for each row execute function public.assistant_set_updated_at();

alter table public.assistant_knowledge enable row level security;
alter table public.assistant_settings enable row level security;
alter table public.assistant_unanswered enable row level security;
alter table public.assistant_feedback enable row level security;
alter table public.assistant_bot_states enable row level security;
alter table public.assistant_admin_knowledge enable row level security;
revoke all on public.assistant_knowledge,public.assistant_settings,public.assistant_unanswered,public.assistant_feedback,public.assistant_bot_states,public.assistant_admin_knowledge from public,anon,authenticated;
grant select,insert,update,delete on public.assistant_knowledge,public.assistant_settings,public.assistant_unanswered,public.assistant_feedback,public.assistant_bot_states,public.assistant_admin_knowledge to service_role;
grant usage,select on sequence public.assistant_unanswered_id_seq,public.assistant_feedback_id_seq to service_role;

do $$ declare t text; begin foreach t in array array['assistant_knowledge','assistant_settings','assistant_unanswered','assistant_feedback','assistant_bot_states','assistant_admin_knowledge'] loop execute format('drop policy if exists %I on public.%I',t||'_browser_deny',t);execute format('create policy %I on public.%I for all to anon,authenticated using(false) with check(false)',t||'_browser_deny',t);end loop;end $$;
commit;
