-- Reproducible baseline for the current eight-table application schema.
-- Safe to run on an empty project; existing production tables are not replaced.

begin;
create extension if not exists pgcrypto;

create or replace function public.zk_set_updated_at() returns trigger language plpgsql set search_path=public,pg_temp as $$begin new.updated_at=now();return new;end$$;
create or replace function public.mask_review_phone(raw_phone text) returns text language sql immutable set search_path=public,pg_temp as $$select case when coalesce(raw_phone,'')='' then '' else left(regexp_replace(raw_phone,'\D','','g'),5)||'xxxx'||right(regexp_replace(raw_phone,'\D','','g'),2) end$$;

create table if not exists public.settings(
 key text primary key,settings jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now()
);
create table if not exists public.submissions(
 id bigint generated by default as identity primary key,full_phone text not null,payload jsonb not null default '{}'::jsonb,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.reviews(
 id bigint generated by default as identity primary key,course_id text not null default 'general',reviewer_name text not null,rating smallint not null default 5 check(rating between 1 and 5),comment text not null default '',status text not null default 'pending' check(status in('pending','approved','rejected')),placements text[] not null default array['course_detail']::text[],created_at timestamptz not null default now(),updated_at timestamptz not null default now(),phone text not null default '',course_ids text[] not null default '{}'::text[],phone_country text default '',public_phone text generated always as(public.mask_review_phone(phone)) stored
);
create table if not exists public.user_questions(
 id bigint generated by default as identity primary key,phone text,question text not null,question_en text,voice_note_url text,answer text,answer_en text,page_source text not null default 'faq',status text not null default 'pending' check(status in('pending','answered','archived')),created_at timestamptz not null default now(),answered_at timestamptz
);
create table if not exists public.page_views(
 id uuid primary key default gen_random_uuid(),page_path text not null,referrer text,user_agent text,created_at timestamptz not null default now()
);
create table if not exists public.error_logs(
 id bigint generated by default as identity primary key,kind text not null default 'error',message text not null default '',stack text,page_path text,user_agent text,lang text,created_at timestamptz not null default now()
);
create table if not exists public.admin_devices(
 id uuid primary key default gen_random_uuid(),owner_phone text not null,device_name text not null default 'دستگاه ناشناس',platform text,browser text,user_agent text not null default '',credential_id text,credential_public_key text,credential_counter bigint not null default 0,biometric_enabled boolean not null default false,is_active boolean not null default true,is_revoked boolean not null default false,last_seen_at timestamptz not null default now(),created_at timestamptz not null default now(),revoked_at timestamptz
);
create table if not exists public.admin_sessions(
 id uuid primary key default gen_random_uuid(),device_id uuid not null references public.admin_devices(id) on delete cascade,owner_phone text not null,token_hash text not null unique,issued_at timestamptz not null default now(),expires_at timestamptz not null default(now()+interval '8 hours'),last_seen_at timestamptz not null default now(),ip_hint text,user_agent text,is_revoked boolean not null default false,revoked_at timestamptz
);

create index if not exists submissions_active_idx on public.submissions(created_at desc) where deleted_at is null;
create index if not exists submissions_phone_idx on public.submissions(full_phone);
create index if not exists reviews_course_idx on public.reviews(course_id,created_at desc);
create index if not exists user_questions_created_idx on public.user_questions(created_at desc);
create index if not exists zkid_page_views_created_at_idx on public.page_views(created_at desc);
create index if not exists admin_devices_seen_idx on public.admin_devices(last_seen_at desc);
create index if not exists admin_sessions_expires_idx on public.admin_sessions(expires_at);
create index if not exists error_logs_created_at_idx on public.error_logs(created_at desc);

drop trigger if exists settings_updated_at on public.settings;create trigger settings_updated_at before update on public.settings for each row execute function public.zk_set_updated_at();
drop trigger if exists submissions_updated_at on public.submissions;create trigger submissions_updated_at before update on public.submissions for each row execute function public.zk_set_updated_at();
drop trigger if exists reviews_updated_at on public.reviews;create trigger reviews_updated_at before update on public.reviews for each row execute function public.zk_set_updated_at();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('images','images',true,8388608,array['image/jpeg','image/png','image/webp','image/gif']),
 ('media','media',true,8388608,array['image/jpeg','image/png','image/webp','image/gif']),
 ('files','files',false,15728640,array['application/pdf']),
 ('voice-notes','voice-notes',false,5242880,array['audio/webm','audio/ogg','audio/mp4','audio/mpeg','audio/wav','video/webm']),
 ('tongue-photos','tongue-photos',false,8388608,array['image/jpeg','image/png','image/webp']),
 ('receipts','receipts',false,6291456,array['image/jpeg','image/png','image/webp'])
on conflict(id) do nothing;

commit;
